import '../models/restaurant.dart';
import '../models/food_item.dart';
import '../models/coupon.dart';

class SampleData {
  static final List<String> categories = [
    'All',
    'Pizza',
    'Burgers',
    'Pakistani',
    'BBQ',
    'Chinese',
    'Fast Food',
    'Biryani',
    'Desserts',
    'Drinks',
    'Breakfast',
    'Healthy',
    'Snacks',
  ];

  static final List<Restaurant> restaurants = [
    Restaurant(
      id: 'r1',
      name: 'Spice Route',
      image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Pakistani',
      rating: 4.8,
      reviewCount: 320,
      deliveryTime: '25-35 min',
      deliveryFee: 99.0,
      minimumOrder: 500.0,
      distance: 2.1,
      featured: true,
      isOpen: true,
      description: 'Authentic traditional Pakistani cuisine, aromatic Dum Biryanis, and rich handi curries.',
      address: '14-C, M.M. Alam Road, Gulberg III, Lahore',
    ),
    Restaurant(
      id: 'r2',
      name: 'Karachi Grill',
      image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=600&q=80',
      cuisine: 'BBQ',
      rating: 4.7,
      reviewCount: 280,
      deliveryTime: '20-30 min',
      deliveryFee: 120.0,
      minimumOrder: 600.0,
      distance: 3.4,
      featured: true,
      isOpen: true,
      description: 'Sizzling charcoal BBQ, melt-in-mouth boti, seekh kababs and smoked platters.',
      address: 'Boat Basin, Block 5, Clifton, Karachi',
    ),
    Restaurant(
      id: 'r3',
      name: 'Urban Bites',
      image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Fast Food',
      rating: 4.6,
      reviewCount: 410,
      deliveryTime: '15-25 min',
      deliveryFee: 80.0,
      minimumOrder: 450.0,
      distance: 1.5,
      featured: true,
      isOpen: true,
      description: 'Contemporary fast food joint serving smashed burgers, crunchy wings, and thick shakes.',
      address: 'Sector F-7 Markaz, Jinnah Super, Islamabad',
    ),
    Restaurant(
      id: 'r4',
      name: 'Burger District',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Burgers',
      rating: 4.9,
      reviewCount: 450,
      deliveryTime: '20-30 min',
      deliveryFee: 99.0,
      minimumOrder: 500.0,
      distance: 1.8,
      featured: true,
      isOpen: true,
      description: 'Hand-crafted gourmet beef and crispy chicken burgers with artisanal brioche buns.',
      address: 'Phase 5 DHA, Commercial Area, Lahore',
    ),
    Restaurant(
      id: 'r5',
      name: 'The Pizza House',
      image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Pizza',
      rating: 4.8,
      reviewCount: 390,
      deliveryTime: '25-35 min',
      deliveryFee: 0.00,
      minimumOrder: 600.0,
      distance: 2.7,
      featured: true,
      isOpen: true,
      description: 'Stone-baked artisanal pizzas loaded with rich mozzarella cheese and fresh toppings.',
      address: 'Kohinoor City, Jaranwala Road, Faisalabad',
    ),
    Restaurant(
      id: 'r6',
      name: 'Royal BBQ',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?auto=format&fit=crop&w=600&q=80',
      cuisine: 'BBQ',
      rating: 4.7,
      reviewCount: 230,
      deliveryTime: '30-40 min',
      deliveryFee: 150.0,
      minimumOrder: 750.0,
      distance: 4.1,
      featured: true,
      isOpen: true,
      description: 'Royal mughlai BBQ delicacies, smoky lamb chops, reshmi boti, and aromatic handi.',
      address: 'SMCHS, Commercial Area, Karachi',
    ),
    Restaurant(
      id: 'r7',
      name: 'Desi Kitchen',
      image: 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Pakistani',
      rating: 4.6,
      reviewCount: 340,
      deliveryTime: '20-30 min',
      deliveryFee: 80.0,
      minimumOrder: 400.0,
      distance: 1.9,
      featured: true,
      isOpen: true,
      description: 'Homestyle Pakistani cooking, authentic Daal Makhni, Palak Paneer, and piping hot rotis.',
      address: 'Mall Road, Saddar, Rawalpindi',
    ),
    Restaurant(
      id: 'r8',
      name: 'China Bowl',
      image: 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Chinese',
      rating: 4.7,
      reviewCount: 290,
      deliveryTime: '25-35 min',
      deliveryFee: 120.0,
      minimumOrder: 550.0,
      distance: 3.0,
      featured: true,
      isOpen: true,
      description: 'Authentic wok-tossed Chinese favorites, fiery Manchurian, Kung Pao, and steaming noodles.',
      address: 'Y Block, DHA Phase 3, Lahore',
    ),
    Restaurant(
      id: 'r9',
      name: 'Sweet Cravings',
      image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Desserts',
      rating: 4.9,
      reviewCount: 480,
      deliveryTime: '15-25 min',
      deliveryFee: 70.0,
      minimumOrder: 350.0,
      distance: 1.6,
      featured: true,
      isOpen: true,
      description: 'Decadent gourmet desserts, Belgian chocolate lava cakes, fudge brownies, and cheesecakes.',
      address: 'Blue Area, Sector G-7, Islamabad',
    ),
    Restaurant(
      id: 'r10',
      name: 'Street Food Co.',
      image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Snacks',
      rating: 4.6,
      reviewCount: 370,
      deliveryTime: '15-25 min',
      deliveryFee: 50.0,
      minimumOrder: 300.0,
      distance: 1.2,
      featured: false,
      isOpen: true,
      description: 'Famous city street food, spicy samosa chaat, crispy rolls, and loaded bun kababs.',
      address: 'Anarkali Bazaar, Old City, Lahore',
    ),
    Restaurant(
      id: 'r11',
      name: 'Green Garden',
      image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Healthy',
      rating: 4.8,
      reviewCount: 210,
      deliveryTime: '20-30 min',
      deliveryFee: 99.0,
      minimumOrder: 450.0,
      distance: 2.4,
      featured: false,
      isOpen: true,
      description: 'Organic health kitchen, fresh Mediterranean salads, protein grain bowls, and detox juices.',
      address: 'Sector F-6 Super Market, Islamabad',
    ),
    Restaurant(
      id: 'r12',
      name: 'Coffee & Co.',
      image: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Drinks',
      rating: 4.9,
      reviewCount: 440,
      deliveryTime: '15-20 min',
      deliveryFee: 80.0,
      minimumOrder: 350.0,
      distance: 1.4,
      featured: true,
      isOpen: true,
      description: 'Premium artisan coffee roastery, specialty pour-overs, chilled frappes, and bakery treats.',
      address: 'Zamzama Commercial Area, DHA Phase 5, Karachi',
    ),
    Restaurant(
      id: 'r13',
      name: 'Food Junction',
      image: 'https://images.unsplash.com/photo-1610440042657-612c34d95e9f?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Fast Food',
      rating: 4.6,
      reviewCount: 310,
      deliveryTime: '20-30 min',
      deliveryFee: 120.0,
      minimumOrder: 500.0,
      distance: 2.2,
      featured: false,
      isOpen: true,
      description: 'Golden crispy fried chicken, giant subs, melted quesadillas, and loaded snacks.',
      address: 'University Road, Gulshan-e-Iqbal, Karachi',
    ),
    Restaurant(
      id: 'r14',
      name: 'Lahore Tikka',
      image: 'https://images.unsplash.com/photo-1599487405270-864f134591a2?auto=format&fit=crop&w=600&q=80',
      cuisine: 'BBQ',
      rating: 4.8,
      reviewCount: 380,
      deliveryTime: '25-35 min',
      deliveryFee: 99.0,
      minimumOrder: 550.0,
      distance: 3.1,
      featured: true,
      isOpen: true,
      description: 'Legendary Lahori charcoal smoke, butter karahi, spicy tikka pieces, and khameeri roti.',
      address: 'Gawalmandi Food Street, Lahore',
    ),
    Restaurant(
      id: 'r15',
      name: 'Daily Dine',
      image: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Breakfast',
      rating: 4.7,
      reviewCount: 260,
      deliveryTime: '15-25 min',
      deliveryFee: 80.0,
      minimumOrder: 400.0,
      distance: 1.7,
      featured: false,
      isOpen: true,
      description: 'Morning bliss with traditional Halwa Puri thalis, fluffy buttermilk pancakes, and eggs.',
      address: 'Main Market, Gulberg II, Lahore',
    ),
  ];

  static final List<FoodItem> foods = [
    // r1: Spice Route (Pakistani)
    FoodItem(
      id: 'f1',
      restaurantId: 'r1',
      name: 'Chicken Biryani',
      description: 'Fragrant basmati rice layered with tender spiced chicken, saffron, and aromatic herbs.',
      image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
      price: 450.0,
      category: 'Biryani',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 142,
      addOns: ['Extra Raita', 'Fresh Salad', 'Boiled Egg', 'Extra Chicken Piece'],
    ),
    FoodItem(
      id: 'f2',
      restaurantId: 'r1',
      name: 'Beef Biryani',
      description: 'Slow-cooked succulent beef chunks infused with traditional spices and aged basmati rice.',
      image: 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?auto=format&fit=crop&w=600&q=80',
      price: 580.0,
      category: 'Biryani',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 98,
      addOns: ['Extra Raita', 'Spicy Chutney', 'Double Beef Cut'],
    ),
    FoodItem(
      id: 'f3',
      restaurantId: 'r1',
      name: 'Chicken Karahi',
      description: 'Fresh chicken cooked in a wok with ripe tomatoes, green chilies, and freshly ground ginger.',
      image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80',
      price: 1350.0,
      category: 'Pakistani',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 185,
      addOns: ['Extra Butter', 'Ginger Garnish', 'Extra Gravy'],
    ),
    FoodItem(
      id: 'f4',
      restaurantId: 'r1',
      name: 'Mutton Karahi',
      description: 'Prime mutton cuts simmered to perfection in a rich tomato base with authentic spices.',
      image: 'https://images.unsplash.com/photo-1545247181-516773cae7be?auto=format&fit=crop&w=600&q=80',
      price: 2200.0,
      category: 'Pakistani',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 88,
      addOns: ['Extra Butter', 'Fresh Green Chilies', 'Desi Ghee Tadka'],
    ),
    FoodItem(
      id: 'f5',
      restaurantId: 'r1',
      name: 'Chicken Handi',
      description: 'Boneless creamy chicken cooked in a traditional clay pot with roasted spices and cream.',
      image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80',
      price: 1150.0,
      category: 'Pakistani',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 115,
      addOns: ['Extra Cream', 'Fried Onions', 'Garlic Naan'],
    ),
    FoodItem(
      id: 'f6',
      restaurantId: 'r1',
      name: 'Chicken Tikka',
      description: 'Juicy quarter chicken marinated in yogurt, tandoori spices, and grilled over live charcoal.',
      image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=600&q=80',
      price: 380.0,
      category: 'BBQ',
      rating: 4.6,
      popular: false,
      available: true,
      reviewCount: 76,
      addOns: ['Mint Sauce', 'Roghani Naan', 'Extra Lemon'],
    ),
    FoodItem(
      id: 'f7',
      restaurantId: 'r1',
      name: 'Seekh Kebab',
      description: 'Finely minced beef blended with coriander, mint, onions, and char-grilled on skewers.',
      image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=600&q=80',
      price: 580.0,
      category: 'BBQ',
      rating: 4.7,
      popular: false,
      available: true,
      reviewCount: 92,
      addOns: ['Extra Chutney', 'Tandoori Paratha', 'Onion Rings'],
    ),
    FoodItem(
      id: 'f8',
      restaurantId: 'r1',
      name: 'Paratha Roll',
      description: 'Crispy pan-fried paratha wrapped around spicy chicken tikka chunks and mint chutney.',
      image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80',
      price: 280.0,
      category: 'Snacks',
      rating: 4.5,
      popular: false,
      available: true,
      reviewCount: 64,
      addOns: ['Garlic Mayo', 'Extra Cheese', 'Spicy Jalapenos'],
    ),
    FoodItem(
      id: 'f9',
      restaurantId: 'r1',
      name: 'Roghani Naan',
      description: 'Fresh tandoori flatbread brushed with butter, sesame seeds, and rich ghee.',
      image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
      price: 280.0,
      category: 'Pakistani',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 110,
      addOns: ['Extra Butter', 'Garlic Topping'],
    ),

    // r2: Karachi Grill (BBQ)
    FoodItem(
      id: 'f10',
      restaurantId: 'r2',
      name: 'Malai Boti',
      description: 'Tender boneless chicken cubes marinated in heavy cream, green chilies, and mild spices.',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?auto=format&fit=crop&w=600&q=80',
      price: 580.0,
      category: 'BBQ',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 210,
      addOns: ['Garlic Mayo Dip', 'Puri Paratha', 'Mint Chutney'],
    ),
    FoodItem(
      id: 'f11',
      restaurantId: 'r2',
      name: 'Beef Seekh Kebab',
      description: 'Juicy spiced minced beef kebabs prepared over slow burning coal embers.',
      image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=600&q=80',
      price: 580.0,
      category: 'BBQ',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Tamarind Sauce', 'Extra Naan', 'Pickled Onions'],
    ),
    FoodItem(
      id: 'f12',
      restaurantId: 'r2',
      name: 'BBQ Platter',
      description: 'Generous feast of Malai Boti, Seekh Kebabs, Chicken Tikka, and fresh naan with dips.',
      image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=600&q=80',
      price: 340.0,
      category: 'BBQ',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 230,
      addOns: ['2x Extra Naan', 'Large Fries', '1.5L Soft Drink'],
    ),
    FoodItem(
      id: 'f13',
      restaurantId: 'r2',
      name: 'Chicken Wings BBQ',
      description: 'Crispy grilled wings tossed in smoky honey BBQ glaze and roasted sesame seeds.',
      image: 'https://images.unsplash.com/photo-1527477378377-50a320649733?auto=format&fit=crop&w=600&q=80',
      price: 380.0,
      category: 'BBQ',
      rating: 4.6,
      popular: false,
      available: true,
      reviewCount: 82,
      addOns: ['Ranch Dressing', 'Extra BBQ Glaze'],
    ),
    FoodItem(
      id: 'f14',
      restaurantId: 'r2',
      name: 'Mutton Ribs Grilled',
      description: 'Mouthwatering spiced mutton ribs char-broiled to tender perfection with herb butter.',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?auto=format&fit=crop&w=600&q=80',
      price: 1250.0,
      category: 'BBQ',
      rating: 4.7,
      popular: false,
      available: true,
      reviewCount: 74,
      addOns: ['Herb Butter', 'Grilled Tomatoes'],
    ),
    FoodItem(
      id: 'f15',
      restaurantId: 'r2',
      name: 'Garlic Butter Naan',
      description: 'Fluffy tandoor naan topped with crushed roasted garlic and pure desi butter.',
      image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
      price: 280.0,
      category: 'Pakistani',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Melted Cheese', 'Coriander Garnish'],
    ),
    FoodItem(
      id: 'f16',
      restaurantId: 'r2',
      name: 'Mint Margarita',
      description: 'Refreshing frosty blend of fresh garden mint, tangy lemon juice, soda, and crushed ice.',
      image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
      price: 220.0,
      category: 'Drinks',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 140,
      addOns: ['Extra Lemon', 'Sugar Free'],
    ),
    FoodItem(
      id: 'f17',
      restaurantId: 'r2',
      name: 'Special Karachi Biryani',
      description: 'Spicy Sindhi-style biryani with succulent chicken, potatoes, and zesty dried plums.',
      image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
      price: 750.0,
      category: 'Biryani',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 180,
      addOns: ['Extra Aloo', 'Zeera Raita', 'Kachumber Salad'],
    ),
    FoodItem(
      id: 'f18',
      restaurantId: 'r2',
      name: 'Chicken Tikka Boti',
      description: 'Spicy skewered boneless chicken cubes charred on charcoal grills with lime.',
      image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=600&q=80',
      price: 580.0,
      category: 'BBQ',
      rating: 4.7,
      popular: false,
      available: true,
      reviewCount: 88,
      addOns: ['Mint Raita', 'Puri Paratha'],
    ),

    // r3: Urban Bites (Fast Food)
    FoodItem(
      id: 'f19',
      restaurantId: 'r3',
      name: 'Zinger Burger',
      description: 'Crispy golden fried chicken breast fillet with spicy secret seasoning, mayo, and lettuce.',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
      price: 520.0,
      category: 'Burgers',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 240,
      addOns: ['Cheddar Cheese Slice', 'Spicy Jalapenos', 'Double Fillet'],
    ),
    FoodItem(
      id: 'f20',
      restaurantId: 'r3',
      name: 'Classic Beef Burger',
      description: 'Juicy seared beef patty with melted cheddar, tomato slices, crunchy pickles, and house sauce.',
      image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=600&q=80',
      price: 680.0,
      category: 'Burgers',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 190,
      addOns: ['Extra Beef Patty', 'Fried Egg', 'Caramelized Onions'],
    ),
    FoodItem(
      id: 'f21',
      restaurantId: 'r3',
      name: 'Crispy Chicken Burger',
      description: 'Golden crumbed chicken patty with tangy cocktail sauce and shredded iceberg on soft bun.',
      image: 'https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?auto=format&fit=crop&w=600&q=80',
      price: 520.0,
      category: 'Burgers',
      rating: 4.6,
      popular: false,
      available: true,
      reviewCount: 110,
      addOns: ['Extra Cheese', 'Honey Mustard Sauce'],
    ),
    FoodItem(
      id: 'f22',
      restaurantId: 'r3',
      name: 'Loaded Cheesy Fries',
      description: 'Crispy french fries drenched in warm cheddar cheese sauce, jalapenos, and minced chicken.',
      image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=600&q=80',
      price: 380.0,
      category: 'Fast Food',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 175,
      addOns: ['Extra Bacon Bits', 'Extra Cheese Sauce', 'Spicy Mayo'],
    ),
    FoodItem(
      id: 'f23',
      restaurantId: 'r3',
      name: 'Crispy Chicken Tenders',
      description: '5 pieces of buttermilk battered chicken tenders served with honey mustard and garlic dip.',
      image: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80',
      price: 250.0,
      category: 'Fast Food',
      rating: 4.5,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Honey Mustard', 'BBQ Sauce Dip'],
    ),
    FoodItem(
      id: 'f24',
      restaurantId: 'r3',
      name: 'Buffalo Hot Wings',
      description: 'Tossed in authentic spicy Buffalo cayenne pepper sauce with celery sticks.',
      image: 'https://images.unsplash.com/photo-1527477378377-50a320649733?auto=format&fit=crop&w=600&q=80',
      price: 380.0,
      category: 'Fast Food',
      rating: 4.6,
      popular: false,
      available: true,
      reviewCount: 88,
      addOns: ['Blue Cheese Dip', 'Ranch Sauce'],
    ),
    FoodItem(
      id: 'f25',
      restaurantId: 'r3',
      name: 'Cold Coffee',
      description: 'Rich chilled espresso blended with milk, creamy ice cream, and chocolate syrup drizzle.',
      image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=600&q=80',
      price: 340.0,
      category: 'Drinks',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 130,
      addOns: ['Whipped Cream', 'Caramel Syrup'],
    ),
    FoodItem(
      id: 'f26',
      restaurantId: 'r3',
      name: 'Chocolate Brownie',
      description: 'Warm fudgy Belgian chocolate brownie with molten core and walnuts.',
      image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80',
      price: 420.0,
      category: 'Desserts',
      rating: 4.6,
      popular: false,
      available: true,
      reviewCount: 105,
      addOns: ['Vanilla Ice Cream Scoop', 'Hot Fudge Drizzle'],
    ),
    FoodItem(
      id: 'f27',
      restaurantId: 'r3',
      name: 'Crispy Onion Rings',
      description: 'Thick sliced sweet onions in beer batter, fried till deep golden brown with dipping sauce.',
      image: 'https://images.unsplash.com/photo-1639024471287-032f6644dd40?auto=format&fit=crop&w=600&q=80',
      price: 250.0,
      category: 'Snacks',
      rating: 4.4,
      popular: false,
      available: true,
      reviewCount: 60,
      addOns: ['Spicy Mayo Dip'],
    ),

    // r4: Burger District (Burgers)
    FoodItem(
      id: 'f28',
      restaurantId: 'r4',
      name: 'Double Patty Burger',
      description: 'Two smashed premium Angus beef patties, double American cheese, caramelized onions, and truffle aioli.',
      image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=600&q=80',
      price: 850.0,
      category: 'Burgers',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 310,
      addOns: ['Extra Patty', 'Crispy Bacon', 'Fried Jalapeno Poppers'],
    ),
    FoodItem(
      id: 'f29',
      restaurantId: 'r4',
      name: 'Cheese Burger Deluxe',
      description: 'Single smashed beef patty, double melted cheddar, diced pickles, ketchup, and secret relish.',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
      price: 450.0,
      category: 'Burgers',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 220,
      addOns: ['Extra Cheese Slice', 'Gluten-Free Bun'],
    ),
    FoodItem(
      id: 'f30',
      restaurantId: 'r4',
      name: 'Smoky BBQ Burger',
      description: 'Beef patty topped with crispy onion rings, smoked cheddar cheese, and bourbon BBQ sauce.',
      image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=600&q=80',
      price: 450.0,
      category: 'Burgers',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 165,
      addOns: ['Extra BBQ Glaze', 'Smoked Bacon'],
    ),
    FoodItem(
      id: 'f31',
      restaurantId: 'r4',
      name: 'Mushroom Swiss Burger',
      description: 'Seared beef patty smothered in sauteed button mushrooms and melted Swiss Emmental cheese.',
      image: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=600&q=80',
      price: 680.0,
      category: 'Burgers',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 140,
      addOns: ['Truffle Oil Drizzle', 'Sauteed Onions'],
    ),
    FoodItem(
      id: 'f32',
      restaurantId: 'r4',
      name: 'Spicy Jalapeno Burger',
      description: 'Flame-broiled beef patty with spicy pepper jack cheese, pickled jalapenos, and chipotle mayo.',
      image: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?auto=format&fit=crop&w=600&q=80',
      price: 450.0,
      category: 'Burgers',
      rating: 4.6,
      popular: false,
      available: true,
      reviewCount: 98,
      addOns: ['Extra Jalapenos', 'Ghost Pepper Sauce'],
    ),
    FoodItem(
      id: 'f33',
      restaurantId: 'r4',
      name: 'Curly Seasoned Fries',
      description: 'Spiral-cut golden potatoes seasoned with paprika, onion powder, and garlic seasoning.',
      image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=600&q=80',
      price: 380.0,
      category: 'Fast Food',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 180,
      addOns: ['Cheddar Cheese Dip', 'Chipotle Mayo'],
    ),
    FoodItem(
      id: 'f34',
      restaurantId: 'r4',
      name: 'Mozzarella Cheese Sticks',
      description: 'Crispy seasoned breadcrumbs coating stretchy molten mozzarella with marinara sauce.',
      image: 'https://images.unsplash.com/photo-1531749668029-2db88e4276c7?auto=format&fit=crop&w=600&q=80',
      price: 250.0,
      category: 'Snacks',
      rating: 4.6,
      popular: false,
      available: true,
      reviewCount: 112,
      addOns: ['Warm Marinara Dip'],
    ),
    FoodItem(
      id: 'f35',
      restaurantId: 'r4',
      name: 'Thick Chocolate Shake',
      description: 'Ultra-creamy handcrafted milkshake made with premium Dutch cocoa and vanilla bean gelato.',
      image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80',
      price: 340.0,
      category: 'Drinks',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 195,
      addOns: ['Whipped Cream', 'Crushed Oreos'],
    ),
    FoodItem(
      id: 'f36',
      restaurantId: 'r4',
      name: 'Iced Latte',
      description: 'Double espresso shot poured over chilled whole milk and crystal ice cubes.',
      image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=600&q=80',
      price: 340.0,
      category: 'Drinks',
      rating: 4.6,
      popular: false,
      available: true,
      reviewCount: 88,
      addOns: ['Vanilla Syrup', 'Oat Milk'],
    ),

    // r5: The Pizza House (Pizza)
    FoodItem(
      id: 'f37',
      restaurantId: 'r5',
      name: 'Chicken Fajita Pizza',
      description: 'Marinated Mexican fajita chicken, crunchy bell peppers, onions, and spicy tomato sauce.',
      image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
      price: 1350.0,
      category: 'Pizza',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 260,
      addOns: ['Cheese Stuffed Crust', 'Extra Jalapenos', 'Garlic Ranch Dip'],
    ),
    FoodItem(
      id: 'f38',
      restaurantId: 'r5',
      name: 'Chicken Tikka Pizza',
      description: 'Desi style spiced chicken tikka chunks, red onions, mozzarella, and green chilies.',
      image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=600&q=80',
      price: 1350.0,
      category: 'Pizza',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 280,
      addOns: ['Cheese Stuffed Crust', 'Extra Chicken Tikka', 'Spicy Dip'],
    ),
    FoodItem(
      id: 'f39',
      restaurantId: 'r5',
      name: 'Pepperoni Pizza',
      description: 'Generous layer of crispy beef pepperoni slices and melted whole milk mozzarella cheese.',
      image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=600&q=80',
      price: 1050.0,
      category: 'Pizza',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 240,
      addOns: ['Double Pepperoni', 'Hot Honey Drizzle'],
    ),
    FoodItem(
      id: 'f40',
      restaurantId: 'r5',
      name: 'Cheese Lover Pizza',
      description: 'Blend of Mozzarella, Parmesan, Cheddar, and Fontina cheese with Italian oregano.',
      image: 'https://images.unsplash.com/photo-1573821663912-569905455b1c?auto=format&fit=crop&w=600&q=80',
      price: 1050.0,
      category: 'Pizza',
      rating: 4.7,
      popular: false,
      available: true,
      reviewCount: 150,
      addOns: ['Extra Mozzarella', 'Garlic Butter Crust'],
    ),
    FoodItem(
      id: 'f41',
      restaurantId: 'r5',
      name: 'BBQ Chicken Pizza',
      description: 'Smoky grilled chicken tossed in sweet BBQ sauce, red onions, cilantro, and smoked gouda.',
      image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
      price: 1350.0,
      category: 'Pizza',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 195,
      addOns: ['Extra BBQ Sauce', 'Crispy Bacon Bits'],
    ),
    FoodItem(
      id: 'f42',
      restaurantId: 'r5',
      name: 'Margherita Pizza',
      description: 'Classic Italian pizza with San Marzano tomato sauce, fresh buffalo mozzarella, and fresh basil leaves.',
      image: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&w=600&q=80',
      price: 1050.0,
      category: 'Pizza',
      rating: 4.6,
      popular: false,
      available: true,
      reviewCount: 120,
      addOns: ['Fresh Basil', 'Extra Virgin Olive Oil'],
    ),
    FoodItem(
      id: 'f43',
      restaurantId: 'r5',
      name: 'Garlic Bread with Cheese',
      description: 'Baguette slices toasted with garlic herb butter and covered in bubbling golden mozzarella.',
      image: 'https://images.unsplash.com/photo-1619535860434-ba1d8fa12536?auto=format&fit=crop&w=600&q=80',
      price: 250.0,
      category: 'Snacks',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 170,
      addOns: ['Marinara Dip Sauce'],
    ),
    FoodItem(
      id: 'f44',
      restaurantId: 'r5',
      name: 'Chicken Calzone',
      description: 'Folded oven-baked pizza stuffed with spicy chicken, ricotta, mushrooms, and mozzarella.',
      image: 'https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?auto=format&fit=crop&w=600&q=80',
      price: 1050.0,
      category: 'Pizza',
      rating: 4.6,
      popular: false,
      available: true,
      reviewCount: 88,
      addOns: ['Extra Dipping Sauce'],
    ),
    FoodItem(
      id: 'f45',
      restaurantId: 'r5',
      name: 'Coke 500ml',
      description: 'Chilled refreshing Coca-Cola bottle.',
      image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80',
      price: 120.0,
      category: 'Drinks',
      rating: 4.5,
      popular: false,
      available: true,
      reviewCount: 130,
      addOns: ['Cup with Ice'],
    ),

    // r6: Royal BBQ (BBQ)
    FoodItem(
      id: 'f46',
      restaurantId: 'r6',
      name: 'Reshmi Kabab',
      description: 'Silky smooth chicken mince infused with cardamom, cream, and egg white, char-grilled lightly.',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?auto=format&fit=crop&w=600&q=80',
      price: 380.0,
      category: 'BBQ',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 190,
      addOns: ['Mint Raita', 'Roghani Naan', 'Extra Lemon'],
    ),
    FoodItem(
      id: 'f47',
      restaurantId: 'r6',
      name: 'Mutton Chops Sizzling',
      description: 'Succulent lamb chops marinated in raw papaya, ginger, garlic, and cracked pepper on a sizzler.',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?auto=format&fit=crop&w=600&q=80',
      price: 1250.0,
      category: 'BBQ',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 165,
      addOns: ['Sizzling Butter', 'Kachumber Salad'],
    ),
    FoodItem(
      id: 'f48',
      restaurantId: 'r6',
      name: 'Chicken Boti Charcoal',
      description: 'Cubed boneless chicken marinated in tandoori spices and roasted over glowing coals.',
      image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=600&q=80',
      price: 580.0,
      category: 'BBQ',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 140,
      addOns: ['Garlic Mayo Dip', 'Puri Paratha'],
    ),
    FoodItem(
      id: 'f49',
      restaurantId: 'r6',
      name: 'Fish Tikka Grill',
      description: 'Boneless tender river fish cubes rubbed with carom seeds, turmeric, and lime juice.',
      image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
      price: 380.0,
      category: 'BBQ',
      rating: 4.6,
      popular: false,
      available: true,
      reviewCount: 85,
      addOns: ['Tartar Dip', 'Extra Lemon'],
    ),
    FoodItem(
      id: 'f50',
      restaurantId: 'r6',
      name: 'Kasturi Boti',
      description: 'Chicken pieces coated in kasuri methi (fenugreek), saffron, and royal aromatic spices.',
      image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=600&q=80',
      price: 580.0,
      category: 'BBQ',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 102,
      addOns: ['Desi Makhan', 'Mint Chutney'],
    ),
    FoodItem(
      id: 'f51',
      restaurantId: 'r6',
      name: 'Kandhari Naan',
      description: 'Large flatbread sprinkled with sesame, fennel seeds, and baked in deep pit tandoor.',
      image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
      price: 280.0,
      category: 'Pakistani',
      rating: 4.7,
      popular: false,
      available: true,
      reviewCount: 90,
      addOns: ['Butter Glaze'],
    ),
    FoodItem(
      id: 'f52',
      restaurantId: 'r6',
      name: 'BBQ Chicken Wings',
      description: 'Skewered marinated chicken wings crisp-cooked on charcoal with spicy glaze.',
      image: 'https://images.unsplash.com/photo-1527477378377-50a320649733?auto=format&fit=crop&w=600&q=80',
      price: 380.0,
      category: 'BBQ',
      rating: 4.5,
      popular: false,
      available: true,
      reviewCount: 78,
      addOns: ['Spicy BBQ Dip'],
    ),
    FoodItem(
      id: 'f53',
      restaurantId: 'r6',
      name: 'Fresh Lemonade',
      description: 'Freshly squeezed lemons with sugar syrup, black salt, and sparkling soda.',
      image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
      price: 220.0,
      category: 'Drinks',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 155,
      addOns: ['Mint Leaves', 'Chia Seeds'],
    ),
    FoodItem(
      id: 'f54',
      restaurantId: 'r6',
      name: 'Matka Kheer',
      description: 'Slow-simmered rice pudding served in earthen clay pots garnished with pistachios and silver leaf.',
      image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=600&q=80',
      price: 350.0,
      category: 'Desserts',
      rating: 4.7,
      popular: false,
      available: true,
      reviewCount: 110,
      addOns: ['Crushed Almonds'],
    ),

    // r7: Desi Kitchen (Pakistani)
    FoodItem(
      id: 'f55',
      restaurantId: 'r7',
      name: 'Chicken Biryani Special',
      description: 'Aromatic basmati rice cooked with whole garam masalas, yogurt chicken, and fried golden onions.',
      image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
      price: 750.0,
      category: 'Biryani',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 230,
      addOns: ['Boiled Egg', 'Zeera Raita', 'Extra Chicken Leg'],
    ),
    FoodItem(
      id: 'f56',
      restaurantId: 'r7',
      name: 'Daal Makhni Handi',
      description: 'Slow-cooked black lentils and kidney beans simmered overnight with butter, cream, and ginger.',
      image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
      price: 1150.0,
      category: 'Pakistani',
      rating: 4.6,
      popular: true,
      available: true,
      reviewCount: 140,
      addOns: ['Extra Butter Dollop', 'Garlic Naan'],
    ),
    FoodItem(
      id: 'f57',
      restaurantId: 'r7',
      name: 'Palak Paneer Desi',
      description: 'Fresh blended spinach puree cooked with fragrant cumin, garlic, and fresh cottage cheese cubes.',
      image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
      price: 480.0,
      category: 'Pakistani',
      rating: 4.7,
      popular: false,
      available: true,
      reviewCount: 115,
      addOns: ['Extra Paneer Cubes', 'Desi Ghee Tadka'],
    ),
    FoodItem(
      id: 'f58',
      restaurantId: 'r7',
      name: 'Mutton Nihari',
      description: 'Traditional slow-cooked shank stew with rich velvety gravy, topped with ginger and lemon.',
      image: 'https://images.unsplash.com/photo-1545247181-516773cae7be?auto=format&fit=crop&w=600&q=80',
      price: 2200.0,
      category: 'Pakistani',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 195,
      addOns: ['Nalli (Bone Marrow)', 'Maghaz (Brain Tadka)', 'Hot Tandoori Naan'],
    ),
    FoodItem(
      id: 'f59',
      restaurantId: 'r7',
      name: 'Beef Haleem',
      description: 'Wholesome porridge of shredded beef, wheat, barley, and lentils slow-cooked for 8 hours.',
      image: 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?auto=format&fit=crop&w=600&q=80',
      price: 480.0,
      category: 'Pakistani',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 155,
      addOns: ['Fried Crispy Onions', 'Chaat Masala & Lemon'],
    ),
    FoodItem(
      id: 'f60',
      restaurantId: 'r7',
      name: 'Tandoori Paratha',
      description: 'Crispy layered flatbread cooked on tandoor walls and basted with melted butter.',
      image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
      price: 250.0,
      category: 'Breakfast',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 130,
      addOns: ['Desi Ghee'],
    ),
    FoodItem(
      id: 'f61',
      restaurantId: 'r7',
      name: 'Chicken Tikka Desi',
      description: 'Quarter chicken char-grilled with traditional spices and mint raita dip.',
      image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=600&q=80',
      price: 380.0,
      category: 'BBQ',
      rating: 4.7,
      popular: false,
      available: true,
      reviewCount: 98,
      addOns: ['Fresh Salad', 'Mint Sauce'],
    ),
    FoodItem(
      id: 'f62',
      restaurantId: 'r7',
      name: 'Gulab Jamun Warm',
      description: 'Soft milk solid dumplings fried to a golden hue and soaked in rose cardamom sugar syrup.',
      image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=600&q=80',
      price: 350.0,
      category: 'Desserts',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 220,
      addOns: ['Extra Pistachio Crumb', '2 Extra Pieces'],
    ),
    FoodItem(
      id: 'f63',
      restaurantId: 'r7',
      name: 'Karak Chai',
      description: 'Strong, aromatic black tea brewed with crushed cardamom, evaporated milk, and cane sugar.',
      image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
      price: 120.0,
      category: 'Drinks',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 260,
      addOns: ['Extra Cardamom', 'Ginger Flavor'],
    ),

    // r8: China Bowl (Chinese)
    FoodItem(
      id: 'f64',
      restaurantId: 'r8',
      name: 'Chicken Chow Mein',
      description: 'Wok-tossed egg noodles with shredded chicken, crunchy cabbage, carrots, bell peppers, and savory soy sauce.',
      image: 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=600&q=80',
      price: 780.0,
      category: 'Chinese',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 215,
      addOns: ['Extra Chicken', 'Spicy Chili Paste', 'Fried Egg on Top'],
    ),
    FoodItem(
      id: 'f65',
      restaurantId: 'r8',
      name: 'Chicken Manchurian',
      description: 'Crispy chicken bites simmered in sweet, spicy, and tangy garlic tomato sauce with egg fried rice.',
      image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=600&q=80',
      price: 780.0,
      category: 'Chinese',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 250,
      addOns: ['Double Gravy', 'Egg Fried Rice Upgrade'],
    ),
    FoodItem(
      id: 'f66',
      restaurantId: 'r8',
      name: 'Kung Pao Chicken',
      description: 'Stir-fried tender chicken with crunchy roasted peanuts, dry red chilies, scallions, and Sichuan sauce.',
      image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=600&q=80',
      price: 780.0,
      category: 'Chinese',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 185,
      addOns: ['Extra Peanuts', 'Extra Spicy'],
    ),
    FoodItem(
      id: 'f67',
      restaurantId: 'r8',
      name: 'Chicken Fried Rice',
      description: 'Wok-seared jasmine rice tossed with scrambled egg, minced chicken, spring onions, and sesame oil.',
      image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80',
      price: 520.0,
      category: 'Chinese',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Fried Egg', 'Chili Garlic Sauce'],
    ),
    FoodItem(
      id: 'f68',
      restaurantId: 'r8',
      name: 'Hot & Sour Soup',
      description: 'Hearty warming broth packed with shredded chicken, black mushrooms, tofu, egg ribbons, and vinegar.',
      image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=600&q=80',
      price: 380.0,
      category: 'Chinese',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 190,
      addOns: ['Crispy Crackers', 'Fish Crackers'],
    ),
    FoodItem(
      id: 'f69',
      restaurantId: 'r8',
      name: 'Beef Chili Dry',
      description: 'Crispy julienne beef strips flash-fried with fresh green chilies, ginger slices, and dark soy.',
      image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=600&q=80',
      price: 780.0,
      category: 'Chinese',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 140,
      addOns: ['Steamed Jasmine Rice', 'Chili Flakes'],
    ),
    FoodItem(
      id: 'f70',
      restaurantId: 'r8',
      name: 'Crispy Spring Rolls',
      description: 'Golden fried vegetable wrappers stuffed with glass noodles, cabbage, and sweet chili dip.',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?auto=format&fit=crop&w=600&q=80',
      price: 280.0,
      category: 'Snacks',
      rating: 4.6,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Sweet Chili Dip Sauce'],
    ),
    FoodItem(
      id: 'f71',
      restaurantId: 'r8',
      name: 'Dynamite Shrimp',
      description: 'Crispy battered shrimp tossed in fiery creamy spicy dynamite sauce and fresh scallions.',
      image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80',
      price: 780.0,
      category: 'Chinese',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 220,
      addOns: ['Extra Dynamite Sauce'],
    ),
    FoodItem(
      id: 'f72',
      restaurantId: 'r8',
      name: 'Green Jasmine Tea',
      description: 'Fragrant hot Chinese jasmine flower tea brewed fresh in a pot.',
      image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
      price: 340.0,
      category: 'Drinks',
      rating: 4.5,
      popular: false,
      available: true,
      reviewCount: 60,
      addOns: ['Honey Sachet'],
    ),

    // r9: Sweet Cravings (Desserts)
    FoodItem(
      id: 'f73',
      restaurantId: 'r9',
      name: 'Chocolate Lava Cake',
      description: 'Warm dark chocolate sponge cake with an irresistible warm molten chocolate flowing center.',
      image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80',
      price: 580.0,
      category: 'Desserts',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 340,
      addOns: ['Vanilla Gelato Scoop', 'Warm Nutella Drizzle', 'Strawberries'],
    ),
    FoodItem(
      id: 'f74',
      restaurantId: 'r9',
      name: 'New York Cheesecake',
      description: 'Creamy Philadelphia cream cheese filling on a buttery Graham cracker crumb base with berry coulis.',
      image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=600&q=80',
      price: 580.0,
      category: 'Desserts',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 280,
      addOns: ['Strawberry Compote', 'Blueberry Coulis'],
    ),
    FoodItem(
      id: 'f75',
      restaurantId: 'r9',
      name: 'Fudge Brownie with Gelato',
      description: 'Triple chocolate fudge brownie served hot with a scoop of Madagascar vanilla bean gelato.',
      image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80',
      price: 420.0,
      category: 'Desserts',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 210,
      addOns: ['Hot Fudge Sauce', 'Caramelized Walnuts'],
    ),
    FoodItem(
      id: 'f76',
      restaurantId: 'r9',
      name: 'Chocolate Truffle Cake Slice',
      description: 'Moist layers of Dutch chocolate cake frosted with silky dark chocolate ganache.',
      image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80',
      price: 350.0,
      category: 'Desserts',
      rating: 4.7,
      popular: false,
      available: true,
      reviewCount: 130,
      addOns: ['Chocolate Shavings'],
    ),
    FoodItem(
      id: 'f77',
      restaurantId: 'r9',
      name: 'Red Velvet Pastry',
      description: 'Ruby red cocoa sponge with rich vanilla cream cheese frosting and white chocolate curls.',
      image: 'https://images.unsplash.com/photo-1586788680434-30d324b2d46f?auto=format&fit=crop&w=600&q=80',
      price: 350.0,
      category: 'Desserts',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 145,
      addOns: ['Raspberry Drizzle'],
    ),
    FoodItem(
      id: 'f78',
      restaurantId: 'r9',
      name: 'Ice Cream Sundae',
      description: 'Three scoops of chocolate, vanilla, and strawberry ice cream topped with fudge, nuts, and cherry.',
      image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=600&q=80',
      price: 420.0,
      category: 'Desserts',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Sprinkles', 'Whipped Cream', 'Extra Cherry'],
    ),
    FoodItem(
      id: 'f79',
      restaurantId: 'r9',
      name: 'Tiramisu Cup',
      description: 'Italian ladyfingers soaked in espresso, layered with whipped mascarpone and dusted with cocoa.',
      image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=600&q=80',
      price: 350.0,
      category: 'Desserts',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 118,
      addOns: ['Espresso Drizzle'],
    ),
    FoodItem(
      id: 'f80',
      restaurantId: 'r9',
      name: 'Iced Caramel Frappe',
      description: 'Blended espresso, creamy milk, buttery caramel syrup, crushed ice, and whipped cream top.',
      image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=600&q=80',
      price: 340.0,
      category: 'Drinks',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 175,
      addOns: ['Caramel Drizzle', 'Extra Shot Espresso'],
    ),
    FoodItem(
      id: 'f81',
      restaurantId: 'r9',
      name: 'Waffle with Nutella',
      description: 'Golden Belgian waffle smothered in warm Nutella hazelnut spread and fresh sliced banana.',
      image: 'https://images.unsplash.com/photo-1562376552-0d160a2f238d?auto=format&fit=crop&w=600&q=80',
      price: 250.0,
      category: 'Breakfast',
      rating: 4.7,
      popular: false,
      available: true,
      reviewCount: 135,
      addOns: ['Vanilla Ice Cream Scoop', 'Extra Strawberries'],
    ),

    // r10: Street Food Co. (Snacks)
    FoodItem(
      id: 'f82',
      restaurantId: 'r10',
      name: 'Special Samosa Chaat',
      description: 'Crushed potato samosas topped with spicy chickpea curry, sweetened yogurt, tamarind and mint chutneys.',
      image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
      price: 250.0,
      category: 'Snacks',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 270,
      addOns: ['Extra Sweet Yogurt', 'Papri Crunch', 'Spicy Chutney'],
    ),
    FoodItem(
      id: 'f83',
      restaurantId: 'r10',
      name: 'Paratha Roll Chicken',
      description: 'Flaky golden paratha stuffed with spicy grilled chicken tikka, thinly sliced onions, and garlic dip.',
      image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80',
      price: 280.0,
      category: 'Snacks',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 210,
      addOns: ['Cheese Slice', 'Double Chicken Fillet'],
    ),
    FoodItem(
      id: 'f84',
      restaurantId: 'r10',
      name: 'Gol Gappay Platter',
      description: '10 crispy semolina puris filled with chickpeas, potatoes, and served with spicy and sweet tamarind water.',
      image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80',
      price: 340.0,
      category: 'Snacks',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 310,
      addOns: ['Extra Khatta Pani', 'Meetha Saunth Pani'],
    ),
    FoodItem(
      id: 'f85',
      restaurantId: 'r10',
      name: 'Dahi Bhallay',
      description: 'Fluffy lentil dumplings submerged in creamy beaten yogurt, roasted cumin, and zesty tamarind chutney.',
      image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
      price: 250.0,
      category: 'Snacks',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 180,
      addOns: ['Crispy Papri', 'Chaat Masala Sprinkle'],
    ),
    FoodItem(
      id: 'f86',
      restaurantId: 'r10',
      name: 'Bun Kabab Special',
      description: 'Street-style lentils and beef patty, beaten egg foam, crunchy onions, and spicy green chutney in a soft bun.',
      image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=600&q=80',
      price: 450.0,
      category: 'Burgers',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 225,
      addOns: ['Extra Fried Egg', 'Cheese Slice'],
    ),
    FoodItem(
      id: 'f87',
      restaurantId: 'r10',
      name: 'Masala Fries Tub',
      description: 'Hot crunchy fries tossed in zesty chaat masala, lemon juice, and secret street spice mix.',
      image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=600&q=80',
      price: 380.0,
      category: 'Fast Food',
      rating: 4.6,
      popular: false,
      available: true,
      reviewCount: 140,
      addOns: ['Garlic Mayo Dip', 'Cheese Sauce'],
    ),
    FoodItem(
      id: 'f88',
      restaurantId: 'r10',
      name: 'Chicken Pakora Basket',
      description: 'Boneless chicken cubes coated in gram flour batter with pomegranate seeds and carom, fried crisp.',
      image: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80',
      price: 250.0,
      category: 'Snacks',
      rating: 4.5,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Mint Raita', 'Chili Sauce'],
    ),
    FoodItem(
      id: 'f89',
      restaurantId: 'r10',
      name: 'Fresh Sweet Lassi',
      description: 'Traditional Punjabi churned yogurt drink topped with a thick layer of malai cream.',
      image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=600&q=80',
      price: 340.0,
      category: 'Drinks',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 190,
      addOns: ['Extra Malai Dollop', 'Crushed Pistachios'],
    ),
    FoodItem(
      id: 'f90',
      restaurantId: 'r10',
      name: 'Mint Lemonade',
      description: 'Crushed ice, fresh mint, freshly squeezed lemons, and rock salt soda.',
      image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
      price: 220.0,
      category: 'Drinks',
      rating: 4.6,
      popular: false,
      available: true,
      reviewCount: 110,
      addOns: ['Extra Lime'],
    ),

    // r11: Green Garden (Healthy)
    FoodItem(
      id: 'f91',
      restaurantId: 'r11',
      name: 'Grilled Chicken Salad',
      description: 'Herb-marinated grilled chicken breast slices on mixed greens, cherry tomatoes, cucumbers, and olive vinaigrette.',
      image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80',
      price: 380.0,
      category: 'Healthy',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Avocado Slices', 'Parmesan Shavings', 'Extra Chicken'],
    ),
    FoodItem(
      id: 'f92',
      restaurantId: 'r11',
      name: 'Quinoa Avocado Bowl',
      description: 'Organic tricolor quinoa, diced ripe avocado, black beans, sweet corn, and lime cilantro dressing.',
      image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
      price: 480.0,
      category: 'Healthy',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 130,
      addOns: ['Grilled Tofu', 'Toasted Pumpkin Seeds'],
    ),
    FoodItem(
      id: 'f93',
      restaurantId: 'r11',
      name: 'Greek Feta Salad',
      description: 'Crisp romaine, Kalamata olives, cucumber rounds, red onions, and authentic Greek feta cubes with oregano.',
      image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=600&q=80',
      price: 480.0,
      category: 'Healthy',
      rating: 4.6,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Extra Feta Cheese', 'Pita Bread Slices'],
    ),
    FoodItem(
      id: 'f94',
      restaurantId: 'r11',
      name: 'Caesar Chicken Wrap',
      description: 'Whole wheat tortilla stuffed with grilled chicken strips, shaved parmesan, romaine, and light Caesar dressing.',
      image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80',
      price: 480.0,
      category: 'Healthy',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 145,
      addOns: ['Greek Yogurt Dip', 'Extra Parmesan'],
    ),
    FoodItem(
      id: 'f95',
      restaurantId: 'r11',
      name: 'Detox Green Cleanse Juice',
      description: 'Cold-pressed green apples, English cucumber, celery stalks, baby spinach, ginger, and lemon.',
      image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
      price: 480.0,
      category: 'Healthy',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 120,
      addOns: ['Chia Seeds', 'Spirulina Boost'],
    ),
    FoodItem(
      id: 'f96',
      restaurantId: 'r11',
      name: 'Chia Seed Berry Pudding',
      description: 'Almond milk soaked chia seeds topped with fresh strawberries, blueberries, and pure organic honey.',
      image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=600&q=80',
      price: 480.0,
      category: 'Healthy',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 88,
      addOns: ['Granola Crunch', 'Flaxseed Powder'],
    ),
    FoodItem(
      id: 'f97',
      restaurantId: 'r11',
      name: 'Fresh Fruit Rainbow Bowl',
      description: 'Seasonal cut mangoes, kiwi slices, pomegranate arils, watermelon, and mint with lime honey dressing.',
      image: 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?auto=format&fit=crop&w=600&q=80',
      price: 250.0,
      category: 'Breakfast',
      rating: 4.6,
      popular: false,
      available: true,
      reviewCount: 75,
      addOns: ['Greek Yogurt', 'Chopped Almonds'],
    ),
    FoodItem(
      id: 'f98',
      restaurantId: 'r11',
      name: 'Protein Power Shake',
      description: 'Whey isolate protein, peanut butter, oat milk, banana, and raw honey blended smooth.',
      image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80',
      price: 340.0,
      category: 'Drinks',
      rating: 4.7,
      popular: false,
      available: true,
      reviewCount: 110,
      addOns: ['Extra Protein Scoop', 'Almond Butter'],
    ),
    FoodItem(
      id: 'f99',
      restaurantId: 'r11',
      name: 'Avocado Toast with Poached Egg',
      description: 'Sourdough toast topped with mashed avocado, chili flakes, sea salt, and a soft poached egg.',
      image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80',
      price: 250.0,
      category: 'Breakfast',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Extra Poached Egg', 'Smoked Salmon'],
    ),

    // r12: Coffee & Co. (Drinks)
    FoodItem(
      id: 'f100',
      restaurantId: 'r12',
      name: 'Iced Spanish Latte',
      description: 'Specialty double espresso poured over condensed milk, chilled milk, and ice for a smooth caramel finish.',
      image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=600&q=80',
      price: 340.0,
      category: 'Drinks',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 310,
      addOns: ['Oat Milk Swap', 'Extra Espresso Shot', 'Vanilla Bean Syrup'],
    ),
    FoodItem(
      id: 'f101',
      restaurantId: 'r12',
      name: 'Cold Coffee Classic',
      description: 'Signature cold brew shaken with fresh cream, whole milk, and organic cane sugar.',
      image: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&w=600&q=80',
      price: 340.0,
      category: 'Drinks',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 220,
      addOns: ['Whipped Cream', 'Chocolate Drizzle'],
    ),
    FoodItem(
      id: 'f102',
      restaurantId: 'r12',
      name: 'Vanilla Caramel Frappe',
      description: 'Blended espresso with French vanilla syrup, butter caramel ribbons, and mountain whipped cream.',
      image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80',
      price: 340.0,
      category: 'Drinks',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 260,
      addOns: ['Extra Caramel Sauce', 'Coffee Jelly'],
    ),
    FoodItem(
      id: 'f103',
      restaurantId: 'r12',
      name: 'Flat White Artisan',
      description: 'Velvety micro-foamed milk poured gracefully over a concentrated double ristretto shot.',
      image: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=600&q=80',
      price: 340.0,
      category: 'Drinks',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 140,
      addOns: ['Almond Milk', 'Extra Shot'],
    ),
    FoodItem(
      id: 'f104',
      restaurantId: 'r12',
      name: 'Fresh Mint Margarita',
      description: 'Ice-blended tangy lime juice, garden fresh mint, black salt, and sparkling citrus soda.',
      image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
      price: 220.0,
      category: 'Drinks',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 180,
      addOns: ['Lemon Slice', 'Sugar Free'],
    ),
    FoodItem(
      id: 'f105',
      restaurantId: 'r12',
      name: 'Peach Iced Tea',
      description: 'Brewed black tea infused with sweet peach nectar and served over crushed crystal ice.',
      image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=600&q=80',
      price: 340.0,
      category: 'Drinks',
      rating: 4.6,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Popping Boba', 'Lemon Wedge'],
    ),
    FoodItem(
      id: 'f106',
      restaurantId: 'r12',
      name: 'Butter Croissant',
      description: 'French layered pastry baked with pure European butter until golden, flaky, and airy.',
      image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=600&q=80',
      price: 250.0,
      category: 'Breakfast',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 190,
      addOns: ['Nutella Dip', 'Strawberry Jam & Butter'],
    ),
    FoodItem(
      id: 'f107',
      restaurantId: 'r12',
      name: 'Blueberry Muffin',
      description: 'Moist golden muffin bursting with sweet wild blueberries and a crunchy sugar crystal top.',
      image: 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?auto=format&fit=crop&w=600&q=80',
      price: 350.0,
      category: 'Desserts',
      rating: 4.7,
      popular: false,
      available: true,
      reviewCount: 120,
      addOns: ['Warm Up Muffin'],
    ),
    FoodItem(
      id: 'f108',
      restaurantId: 'r12',
      name: 'Cinnamon Roll',
      description: 'Warm fluffy swirl infused with aromatic Ceylon cinnamon and glazed in rich cream cheese icing.',
      image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
      price: 350.0,
      category: 'Desserts',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 170,
      addOns: ['Extra Cream Cheese Glaze', 'Pecans'],
    ),

    // r13: Food Junction (Fast Food)
    FoodItem(
      id: 'f109',
      restaurantId: 'r13',
      name: 'Crispy Fried Chicken 3pcs',
      description: '3 large pieces of fresh chicken marinated in 11 secret herbs and fried extra crispy.',
      image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80',
      price: 250.0,
      category: 'Fast Food',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 230,
      addOns: ['Garlic Mayo Dip', 'Dinner Roll', 'Coleslaw Cup'],
    ),
    FoodItem(
      id: 'f110',
      restaurantId: 'r13',
      name: 'Zinger Supreme Burger',
      description: 'Spicy chicken fillet, melted cheddar cheese slice, fresh lettuce, and spicy chipotle sauce.',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
      price: 520.0,
      category: 'Burgers',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 185,
      addOns: ['Cheese Slice', 'Double Fillet', 'Jalapenos'],
    ),
    FoodItem(
      id: 'f111',
      restaurantId: 'r13',
      name: 'Chicken Cheese Sub',
      description: '10 inch Italian sub loaf packed with grilled chicken breast, peppers, and melted provolone.',
      image: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=600&q=80',
      price: 250.0,
      category: 'Fast Food',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Extra Melted Cheese', 'Chipotle Dressing'],
    ),
    FoodItem(
      id: 'f112',
      restaurantId: 'r13',
      name: 'Cheesy Pizza Fries',
      description: 'Crinkle-cut french fries baked under marinara, mozzarella cheese, and chicken chunks.',
      image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=600&q=80',
      price: 1050.0,
      category: 'Fast Food',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 195,
      addOns: ['Black Olives', 'Extra Mozzarella'],
    ),
    FoodItem(
      id: 'f113',
      restaurantId: 'r13',
      name: 'Chicken Quesadilla',
      description: 'Toasted flour tortilla stuffed with spiced shredded chicken, Mexican cheese blend, and salsa.',
      image: 'https://images.unsplash.com/photo-1618040996337-56904b7850b9?auto=format&fit=crop&w=600&q=80',
      price: 250.0,
      category: 'Fast Food',
      rating: 4.6,
      popular: false,
      available: true,
      reviewCount: 105,
      addOns: ['Sour Cream Dip', 'Guacamole'],
    ),
    FoodItem(
      id: 'f114',
      restaurantId: 'r13',
      name: 'Crispy Popcorn Chicken',
      description: 'Bite-sized tender chicken nuggets seasoned with Cajun spices and fried crunchy.',
      image: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80',
      price: 250.0,
      category: 'Snacks',
      rating: 4.5,
      popular: false,
      available: true,
      reviewCount: 120,
      addOns: ['Honey BBQ Sauce', 'Spicy Garlic Mayo'],
    ),
    FoodItem(
      id: 'f115',
      restaurantId: 'r13',
      name: 'Mozzarella Dippers',
      description: 'Golden fried herb-crumbed cheese batons with marinara dipping sauce.',
      image: 'https://images.unsplash.com/photo-1531749668029-2db88e4276c7?auto=format&fit=crop&w=600&q=80',
      price: 250.0,
      category: 'Snacks',
      rating: 4.6,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Warm Marinara Sauce'],
    ),
    FoodItem(
      id: 'f116',
      restaurantId: 'r13',
      name: 'Chilled Pepsi 500ml',
      description: 'Ice cold carbonated Pepsi bottle.',
      image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80',
      price: 120.0,
      category: 'Drinks',
      rating: 4.5,
      popular: false,
      available: true,
      reviewCount: 88,
      addOns: ['Cup with Ice'],
    ),
    FoodItem(
      id: 'f117',
      restaurantId: 'r13',
      name: 'Double Cheeseburger',
      description: 'Two grilled beef patties with melted cheddar cheese, lettuce, and secret diner sauce.',
      image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=600&q=80',
      price: 850.0,
      category: 'Burgers',
      rating: 4.7,
      popular: false,
      available: true,
      reviewCount: 110,
      addOns: ['Extra Cheese', 'Bacon Bits'],
    ),

    // r14: Lahore Tikka (BBQ)
    FoodItem(
      id: 'f118',
      restaurantId: 'r14',
      name: 'Special Lahore Chicken Tikka',
      description: 'Generous chicken quarter marinated with traditional Lahori red spices, grilled on open coals.',
      image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=600&q=80',
      price: 380.0,
      category: 'BBQ',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 320,
      addOns: ['Khameeri Roti', 'Mint Raita', 'Extra Lemon Slice'],
    ),
    FoodItem(
      id: 'f119',
      restaurantId: 'r14',
      name: 'Malai Boti Skewers',
      description: 'Boneless chicken cubes soaked in clotted cream, white pepper, and coriander, barbecued over slow fire.',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?auto=format&fit=crop&w=600&q=80',
      price: 580.0,
      category: 'BBQ',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 260,
      addOns: ['Puri Paratha', 'Special Garlic Dip'],
    ),
    FoodItem(
      id: 'f120',
      restaurantId: 'r14',
      name: 'Seekh Kebab Lahori',
      description: 'Minced beef kebabs seasoned with fried onions, crushed pomegranate seeds, and fresh mint.',
      image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=600&q=80',
      price: 580.0,
      category: 'BBQ',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 210,
      addOns: ['Tandoori Roti', 'Zeera Raita'],
    ),
    FoodItem(
      id: 'f121',
      restaurantId: 'r14',
      name: 'Lahori Mutton Karahi',
      description: 'Tender baby mutton pieces prepared in pure butter with green chilies, tomatoes, and ginger julienne.',
      image: 'https://images.unsplash.com/photo-1545247181-516773cae7be?auto=format&fit=crop&w=600&q=80',
      price: 2200.0,
      category: 'Pakistani',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 240,
      addOns: ['Extra Desi Makhan', 'Fresh Ginger Garnish'],
    ),
    FoodItem(
      id: 'f122',
      restaurantId: 'r14',
      name: 'Chicken Shinwari Karahi',
      description: 'Peshawari Shinwari style chicken cooked solely with black pepper, green chilies, and ripe tomatoes.',
      image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80',
      price: 1350.0,
      category: 'Pakistani',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 190,
      addOns: ['Animal Fat Tadka (Traditional)', 'Extra Green Chilies'],
    ),
    FoodItem(
      id: 'f123',
      restaurantId: 'r14',
      name: 'Chicken Biryani Pot',
      description: 'Steaming clay pot dum biryani with marinated chicken pieces and saffron scented rice.',
      image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
      price: 450.0,
      category: 'Biryani',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 230,
      addOns: ['Zeera Raita', 'Aloo Bukhara Chutney'],
    ),
    FoodItem(
      id: 'f124',
      restaurantId: 'r14',
      name: 'Khameeri Roti',
      description: 'Leavened soft Lahori tandoori flatbread, soft and airy on the inside with a crisp crust.',
      image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
      price: 280.0,
      category: 'Pakistani',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 150,
      addOns: ['Butter Topping'],
    ),
    FoodItem(
      id: 'f125',
      restaurantId: 'r14',
      name: 'Zeera Raita & Kachumber',
      description: 'Chilled spiced yogurt with roasted cumin and diced cucumbers, onions, and tomatoes.',
      image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
      price: 280.0,
      category: 'Pakistani',
      rating: 4.7,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Extra Mint'],
    ),
    FoodItem(
      id: 'f126',
      restaurantId: 'r14',
      name: 'Fresh Mint Margarita',
      description: 'Crushed iced beverage with garden mint, fresh lime, soda, and Himalayan pink salt.',
      image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
      price: 220.0,
      category: 'Drinks',
      rating: 4.7,
      popular: false,
      available: true,
      reviewCount: 110,
      addOns: ['Extra Lime'],
    ),

    // r15: Daily Dine (Breakfast)
    FoodItem(
      id: 'f127',
      restaurantId: 'r15',
      name: 'Halwa Puri Special Thali',
      description: '3 hot crispy puris, spicy chickpea chana salan, sweet suji halwa, and spicy mixed pickle.',
      image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
      price: 250.0,
      category: 'Breakfast',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 290,
      addOns: ['2x Extra Puris', 'Aloo Bhujia Cup', 'Extra Sweet Halwa'],
    ),
    FoodItem(
      id: 'f128',
      restaurantId: 'r15',
      name: 'Fluffy Buttermilk Pancakes',
      description: 'Stack of three golden fluffy pancakes with whipped butter, maple syrup, and fresh berries.',
      image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=600&q=80',
      price: 350.0,
      category: 'Breakfast',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 210,
      addOns: ['Pure Maple Syrup', 'Nutella Drizzle', 'Extra Butter'],
    ),
    FoodItem(
      id: 'f129',
      restaurantId: 'r15',
      name: 'Cheesy Mushroom Omelette',
      description: '3 farm fresh eggs folded with sauteed button mushrooms, cheddar cheese, and fresh chives, served with toast.',
      image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80',
      price: 250.0,
      category: 'Breakfast',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 175,
      addOns: ['Hash Brown Side', 'Extra Cheddar Cheese'],
    ),
    FoodItem(
      id: 'f130',
      restaurantId: 'r15',
      name: 'Crispy French Toast',
      description: 'Brioche bread soaked in vanilla cinnamon custard, pan-fried crisp with powdered sugar and maple syrup.',
      image: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=600&q=80',
      price: 250.0,
      category: 'Breakfast',
      rating: 4.6,
      popular: false,
      available: true,
      reviewCount: 130,
      addOns: ['Vanilla Gelato Scoop', 'Fresh Strawberries'],
    ),
    FoodItem(
      id: 'f131',
      restaurantId: 'r15',
      name: 'Desi Anda Paratha',
      description: 'Crisp golden layered tandoori paratha served with two sunny side up or masala fried eggs.',
      image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
      price: 250.0,
      category: 'Breakfast',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 220,
      addOns: ['Extra Fried Egg', 'Desi Ghee Paratha Upgrade'],
    ),
    FoodItem(
      id: 'f132',
      restaurantId: 'r15',
      name: 'Shakshuka Poached Eggs',
      description: 'Two eggs gently poached in a simmering skillet of spiced tomatoes, bell peppers, garlic, and feta with pita.',
      image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?auto=format&fit=crop&w=600&q=80',
      price: 250.0,
      category: 'Breakfast',
      rating: 4.7,
      popular: false,
      available: true,
      reviewCount: 115,
      addOns: ['Warm Pita Bread', 'Extra Feta Cheese'],
    ),
    FoodItem(
      id: 'f133',
      restaurantId: 'r15',
      name: 'Doodh Patti Karak Chai',
      description: 'Slow simmered rich milk tea brewed with crushed green cardamom and Assam black tea leaves.',
      image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
      price: 120.0,
      category: 'Drinks',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 280,
      addOns: ['Cardamom Pods', 'Malai Layer'],
    ),
    FoodItem(
      id: 'f134',
      restaurantId: 'r15',
      name: 'Fresh Orange Juice',
      description: '100% freshly squeezed sweet Valencia oranges with no added sugar or water.',
      image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=600&q=80',
      price: 340.0,
      category: 'Drinks',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 140,
      addOns: ['Extra Pulp', 'No Ice'],
    ),
    FoodItem(
      id: 'f135',
      restaurantId: 'r15',
      name: 'Fruit Yogurt Bowl',
      description: 'Creamy Greek yogurt layered with wild honey, crunchy oat granola, kiwi, and seasonal berries.',
      image: 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?auto=format&fit=crop&w=600&q=80',
      price: 480.0,
      category: 'Healthy',
      rating: 4.6,
      popular: false,
      available: true,
      reviewCount: 92,
      addOns: ['Chia Seeds', 'Almond Butter'],
    ),
  ];

  static final List<Coupon> coupons = [
    Coupon(code: 'WELCOME10', discountValue: 10.0, isPercentage: true, minOrderAmount: 500.0),
    Coupon(code: 'FEAST20', discountValue: 20.0, isPercentage: true, minOrderAmount: 1000.0),
    Coupon(code: 'FREESHIP', discountValue: 150.0, isPercentage: false, minOrderAmount: 600.0),
    Coupon(code: 'BIRYANI15', discountValue: 15.0, isPercentage: true, minOrderAmount: 600.0),
  ];

  static List<Restaurant> getRestaurantsForCategory(String category) {
    if (category == 'All') return List<Restaurant>.from(restaurants);
    final catLower = category.toLowerCase().trim();
    return restaurants.where((r) {
      if (r.cuisine.toLowerCase() == catLower) return true;
      if (r.cuisine.toLowerCase().contains(catLower)) return true;
      return foods.any((f) =>
          f.restaurantId == r.id &&
          (f.category.toLowerCase() == catLower ||
              f.category.toLowerCase().contains(catLower) ||
              f.name.toLowerCase().contains(catLower)));
    }).toList();
  }

  static List<FoodItem> getFoodsForCategory(String category) {
    if (category == 'All') return List<FoodItem>.from(foods);
    final catLower = category.toLowerCase().trim();
    return foods.where((f) =>
        f.category.toLowerCase() == catLower ||
        f.category.toLowerCase().contains(catLower) ||
        f.name.toLowerCase().contains(catLower)).toList();
  }

  static List<FoodItem> getPopularDishes() {
    return foods.where((f) => f.popular).toList();
  }

  static Restaurant? getRestaurantById(String id) {
    try {
      return restaurants.firstWhere((r) => r.id == id);
    } catch (_) {
      return null;
    }
  }
}
