import '../models/restaurant.dart';
import '../models/food_item.dart';
import '../models/coupon.dart';

class SampleData {
  static final List<String> categories = [
    'All',
    'Biryani',
    'BBQ',
    'Burgers',
    'Pizza',
    'Pakistani',
    'Shawarma',
    'Chinese',
    'Fast Food',
    'Tea/Coffee',
    'Bakery',
    'Desserts',
    'Healthy',
    'Breakfast',
    'Home Kitchen',
    'Drinks',
  ];

  static final List<Restaurant> restaurants = [
    Restaurant(
      id: 'r1',
      name: 'Al-Noor Dum Biryani & Pulao',
      image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Biryani',
      rating: 4.8,
      reviewCount: 420,
      deliveryTime: '20-30 min',
      deliveryFee: 70.0,
      minimumOrder: 400.0,
      distance: 1.8,
      featured: true,
      isPopular: true,
      isOpen: true,
      description: 'Bahawalpur’s famed aromatic Zafrani dum biryani, beef yakhni pulao, and spicy raita.',
      address: 'Farid Gate Chowk, Bahawalpur',
      area: 'Farid Gate',
      offer: '15% OFF',
    ),
    Restaurant(
      id: 'r2',
      name: 'Sultani BBQ & Charcoal Grill',
      image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=600&q=80',
      cuisine: 'BBQ',
      rating: 4.9,
      reviewCount: 530,
      deliveryTime: '25-35 min',
      deliveryFee: 99.0,
      minimumOrder: 500.0,
      distance: 2.3,
      featured: true,
      isPopular: true,
      isOpen: true,
      description: 'Sizzling reshmi kababs, charcoal chicken tikka boti, mutton chops, and tandoori parathas.',
      address: 'Circular Road, Near Dring Stadium, Bahawalpur',
      area: 'Circular Road',
      offer: '20% OFF',
    ),
    Restaurant(
      id: 'r3',
      name: 'Grill Town Smashed Burgers',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Burgers',
      rating: 4.7,
      reviewCount: 340,
      deliveryTime: '15-25 min',
      deliveryFee: 80.0,
      minimumOrder: 450.0,
      distance: 1.2,
      featured: true,
      isPopular: true,
      isOpen: true,
      description: 'Artisanal smashed beef patties, crunchy zinger stacks, melted cheddar, and secret signature dip.',
      address: 'Aziz Bhatti Shaheed Road, Cantt, Bahawalpur',
      area: 'Cantt',
      offer: 'Rs. 100 OFF',
    ),
    Restaurant(
      id: 'r4',
      name: 'The Pizza Crust Studio',
      image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Pizza',
      rating: 4.8,
      reviewCount: 460,
      deliveryTime: '25-35 min',
      deliveryFee: 0.0,
      minimumOrder: 600.0,
      distance: 2.1,
      featured: true,
      isPopular: true,
      isOpen: true,
      description: 'Hand-tossed thin crust & stuffed crust pizzas smothered in creamy mozzarella and smoked meats.',
      address: 'Main Commercial Area, Satellite Town, Bahawalpur',
      area: 'Commercial Area',
      offer: 'Free Delivery',
    ),
    Restaurant(
      id: 'r5',
      name: 'Al-Madina Shawarma & Broast',
      image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Shawarma',
      rating: 4.6,
      reviewCount: 310,
      deliveryTime: '15-20 min',
      deliveryFee: 50.0,
      minimumOrder: 300.0,
      distance: 1.1,
      featured: false,
      isPopular: true,
      isOpen: true,
      description: 'Authentic Syrian spiced chicken shawarma platters, garlic tahini wraps, and crispy quarter broast.',
      address: 'Opposite IUB Gate 1, University Road, Bahawalpur',
      area: 'University Road',
      offer: 'Buy 1 Get 1',
    ),
    Restaurant(
      id: 'r6',
      name: 'Golden Dragon Chinese Bowl',
      image: 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Chinese',
      rating: 4.7,
      reviewCount: 290,
      deliveryTime: '25-35 min',
      deliveryFee: 90.0,
      minimumOrder: 550.0,
      distance: 2.8,
      featured: true,
      isPopular: false,
      isOpen: true,
      description: 'Fiery Chicken Manchurian, Kung Pao, egg fried rice, spring rolls, and wok-tossed chow mein.',
      address: 'Block C, Model Town, Bahawalpur',
      area: 'Model Town',
      offer: '10% OFF',
    ),
    Restaurant(
      id: 'r7',
      name: 'Rooster Crispy Fried Chicken',
      image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Fast Food',
      rating: 4.8,
      reviewCount: 490,
      deliveryTime: '15-25 min',
      deliveryFee: 60.0,
      minimumOrder: 400.0,
      distance: 1.4,
      featured: true,
      isPopular: true,
      isOpen: true,
      description: 'Golden crunch fried chicken drumsticks, spicy popcorn nuggets, and loaded cheese curly fries.',
      address: 'Dubai Chowk Commercial Hub, Bahawalpur',
      area: 'Dubai Chowk',
      offer: 'Rs. 150 OFF',
    ),
    Restaurant(
      id: 'r8',
      name: 'Chai Shai & Cafe Khana',
      image: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Tea/Coffee',
      rating: 4.9,
      reviewCount: 380,
      deliveryTime: '15-20 min',
      deliveryFee: 50.0,
      minimumOrder: 300.0,
      distance: 1.5,
      featured: false,
      isPopular: true,
      isOpen: true,
      description: 'Karak Doodh Patti chai, Kashmiri pink tea, spiced parathas, Spanish lattes, and club sandwiches.',
      address: 'Cantt Market, Near Officers Club, Bahawalpur',
      area: 'Cantt',
      offer: null,
    ),
    Restaurant(
      id: 'r9',
      name: 'Royal Sweets & Bakers',
      image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Bakery',
      rating: 4.8,
      reviewCount: 560,
      deliveryTime: '15-25 min',
      deliveryFee: 60.0,
      minimumOrder: 350.0,
      distance: 1.9,
      featured: true,
      isPopular: false,
      isOpen: true,
      description: 'Traditional Bahawalpuri Sohan Halwa, freshly baked pastries, dry fruit biscuits, and tea cakes.',
      address: 'Shahi Bazaar, Farid Gate, Bahawalpur',
      area: 'Farid Gate',
      offer: '10% OFF',
    ),
    Restaurant(
      id: 'r10',
      name: 'Sweet Tooth Gelato & Waffles',
      image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Desserts',
      rating: 4.9,
      reviewCount: 430,
      deliveryTime: '15-20 min',
      deliveryFee: 70.0,
      minimumOrder: 350.0,
      distance: 1.6,
      featured: true,
      isPopular: true,
      isOpen: true,
      description: 'Belgian chocolate lava cakes, Nutella waffle sticks, gourmet sundae tubs, and Lotus milkshakes.',
      address: 'Model Town A, Near Central Park, Bahawalpur',
      area: 'Model Town',
      offer: '15% OFF',
    ),
    Restaurant(
      id: 'r11',
      name: 'Green Leaf Fresh Bowls & Juices',
      image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Healthy',
      rating: 4.7,
      reviewCount: 220,
      deliveryTime: '20-30 min',
      deliveryFee: 80.0,
      minimumOrder: 450.0,
      distance: 2.4,
      featured: false,
      isPopular: false,
      isOpen: true,
      description: 'Protein power bowls, fresh Greek salads, beetroot cleanse juices, and cold-pressed citrus blends.',
      address: 'Mall Road, Cantt, Bahawalpur',
      area: 'Cantt',
      offer: 'Free Delivery',
    ),
    Restaurant(
      id: 'r12',
      name: 'Morning Glory Halwa Puri & Nashta',
      image: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Breakfast',
      rating: 4.8,
      reviewCount: 400,
      deliveryTime: '15-25 min',
      deliveryFee: 50.0,
      minimumOrder: 300.0,
      distance: 1.3,
      featured: false,
      isPopular: true,
      isOpen: true,
      description: 'Piping hot crispy puris, chana masala, sweet suji halwa, lassi, and Desi omelette parathas.',
      address: 'Circular Road, Near Welcome Gate, Bahawalpur',
      area: 'Circular Road',
      offer: null,
    ),
    Restaurant(
      id: 'r13',
      name: 'Mama\'s Secret Home Kitchen',
      image: 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Home Kitchen',
      rating: 4.9,
      reviewCount: 350,
      deliveryTime: '25-35 min',
      deliveryFee: 60.0,
      minimumOrder: 400.0,
      distance: 1.7,
      featured: true,
      isPopular: true,
      isOpen: true,
      description: 'Pure home-style cooking: Daal Chawal thali, Palak Gosht, Aloo Keema, and tawa phulkas.',
      address: 'Street 4, Islamia Colony, Bahawalpur',
      area: 'Islamia Colony',
      offer: 'Rs. 200 OFF',
    ),
    Restaurant(
      id: 'r14',
      name: 'Shinwari Dera & Karahi',
      image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Pakistani',
      rating: 4.8,
      reviewCount: 620,
      deliveryTime: '30-40 min',
      deliveryFee: 120.0,
      minimumOrder: 800.0,
      distance: 3.5,
      featured: true,
      isPopular: true,
      isOpen: true,
      description: 'Authentic Namkeen Shinwari mutton karahi cooked in lamb fat with tomatoes and organic sea salt.',
      address: 'Model Town C, Near Bypass, Bahawalpur',
      area: 'Model Town',
      offer: '20% OFF',
    ),
    Restaurant(
      id: 'r15',
      name: 'Karachi Student Biryani Hub',
      image: 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Biryani',
      rating: 4.6,
      reviewCount: 470,
      deliveryTime: '20-30 min',
      deliveryFee: 70.0,
      minimumOrder: 350.0,
      distance: 2.0,
      featured: false,
      isPopular: true,
      isOpen: true,
      description: 'Spicy Karachi-style potato chicken biryani, zarda, mint raita, and shami kabab add-ons.',
      address: 'Commercial Market, Satellite Town, Bahawalpur',
      area: 'Satellite Town',
      offer: '15% OFF',
    ),
    Restaurant(
      id: 'r16',
      name: 'Bahaar-e-Kabab Smokey BBQ',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?auto=format&fit=crop&w=600&q=80',
      cuisine: 'BBQ',
      rating: 4.7,
      reviewCount: 290,
      deliveryTime: '25-35 min',
      deliveryFee: 90.0,
      minimumOrder: 500.0,
      distance: 2.2,
      featured: false,
      isPopular: false,
      isOpen: true,
      description: 'Mughlai beef gola kababs, chicken malai tikka, spicy seekh kababs, and khameeri kulchas.',
      address: 'Old City, Near Farid Gate, Bahawalpur',
      area: 'Farid Gate',
      offer: null,
    ),
    Restaurant(
      id: 'r17',
      name: 'Burger District 6',
      image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Burgers',
      rating: 4.8,
      reviewCount: 390,
      deliveryTime: '15-25 min',
      deliveryFee: 80.0,
      minimumOrder: 450.0,
      distance: 1.5,
      featured: true,
      isPopular: true,
      isOpen: true,
      description: 'Crispy fillet burgers, jalapeno beef melt, waffle potato fries, and loaded garlic mayo dips.',
      address: 'Shop 12, Commercial Plaza, Bahawalpur',
      area: 'Commercial Area',
      offer: 'Free Delivery',
    ),
    Restaurant(
      id: 'r18',
      name: 'Napoli Stone-Oven Pizza',
      image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Pizza',
      rating: 4.9,
      reviewCount: 410,
      deliveryTime: '25-35 min',
      deliveryFee: 99.0,
      minimumOrder: 600.0,
      distance: 2.6,
      featured: true,
      isPopular: false,
      isOpen: true,
      description: 'Neapolitan charred crust pizzas, buffalo mozzarella, fresh basil, pepperoni, and hot honey drizzle.',
      address: 'Main Boulevard, Model Town B, Bahawalpur',
      area: 'Model Town',
      offer: '20% OFF',
    ),
    Restaurant(
      id: 'r19',
      name: 'Damascus Pita & Shawarma',
      image: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Shawarma',
      rating: 4.7,
      reviewCount: 320,
      deliveryTime: '15-20 min',
      deliveryFee: 50.0,
      minimumOrder: 300.0,
      distance: 1.3,
      featured: false,
      isPopular: true,
      isOpen: true,
      description: 'Levantine spiced chicken wraps, open hummus platters, crispy falafel boxes, and garlic toum.',
      address: 'Ahmedpur East Road, Dubai Chowk, Bahawalpur',
      area: 'Dubai Chowk',
      offer: null,
    ),
    Restaurant(
      id: 'r20',
      name: 'Mandarin Wok & Dimsum',
      image: 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Chinese',
      rating: 4.6,
      reviewCount: 240,
      deliveryTime: '25-35 min',
      deliveryFee: 100.0,
      minimumOrder: 550.0,
      distance: 3.1,
      featured: false,
      isPopular: false,
      isOpen: true,
      description: 'Steamed chicken dumplings, Szechuan crispy beef, hot & sour soup, and Singaporean rice noodles.',
      address: 'Cantt Plaza, Main Cantt, Bahawalpur',
      area: 'Cantt',
      offer: '10% OFF',
    ),
    Restaurant(
      id: 'r21',
      name: 'The Crave Yard Fast Food',
      image: 'https://images.unsplash.com/photo-1610440042657-612c34d95e9f?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Fast Food',
      rating: 4.7,
      reviewCount: 360,
      deliveryTime: '15-25 min',
      deliveryFee: 60.0,
      minimumOrder: 400.0,
      distance: 1.4,
      featured: false,
      isPopular: true,
      isOpen: true,
      description: 'Crispy chicken tenders, cheesy pizza fries, spicy chapli burgers, and frozen lime chillers.',
      address: 'Near Baghdad-ul-Jadeed Campus, Bahawalpur',
      area: 'University Road',
      offer: 'Rs. 100 OFF',
    ),
    Restaurant(
      id: 'r22',
      name: 'Coffee Lounge & Roastery',
      image: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Tea/Coffee',
      rating: 4.9,
      reviewCount: 420,
      deliveryTime: '15-20 min',
      deliveryFee: 70.0,
      minimumOrder: 350.0,
      distance: 1.8,
      featured: true,
      isPopular: false,
      isOpen: true,
      description: 'Specialty espresso roasts, iced caramel macchiatos, cold brews, and buttery croissants.',
      address: 'Sector A, Model Town, Bahawalpur',
      area: 'Model Town',
      offer: null,
    ),
    Restaurant(
      id: 'r23',
      name: 'Bake O’ Clock Artisan Patisserie',
      image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Bakery',
      rating: 4.8,
      reviewCount: 300,
      deliveryTime: '20-30 min',
      deliveryFee: 60.0,
      minimumOrder: 350.0,
      distance: 2.1,
      featured: false,
      isPopular: false,
      isOpen: true,
      description: 'Artisan sourdough loaves, red velvet cupcakes, lotus cheesecakes, and savory chicken patties.',
      address: 'Block B, Satellite Town, Bahawalpur',
      area: 'Satellite Town',
      offer: 'Free Delivery',
    ),
    Restaurant(
      id: 'r24',
      name: 'Fit & Fine Healthy Kitchen',
      image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Healthy',
      rating: 4.7,
      reviewCount: 190,
      deliveryTime: '20-30 min',
      deliveryFee: 80.0,
      minimumOrder: 450.0,
      distance: 2.5,
      featured: false,
      isPopular: false,
      isOpen: true,
      description: 'Grilled lemon herb chicken breast, quinoa avocado salads, low-carb wraps, and detox shakes.',
      address: 'Commercial Area Phase 1, Bahawalpur',
      area: 'Commercial Area',
      offer: '15% OFF',
    ),
    Restaurant(
      id: 'r25',
      name: 'Desi Dastarkhwan Handi & Karahi',
      image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80',
      cuisine: 'Pakistani',
      rating: 4.8,
      reviewCount: 530,
      deliveryTime: '25-35 min',
      deliveryFee: 80.0,
      minimumOrder: 500.0,
      distance: 1.9,
      featured: true,
      isPopular: true,
      isOpen: true,
      description: 'Rich boneless chicken makhni handi, spicy mutton brain masala, daal mash fry, and garlic naan.',
      address: 'Near Railway Station Road, Dubai Chowk, Bahawalpur',
      area: 'Dubai Chowk',
      offer: '25% OFF',
    ),
  ];

  static final List<FoodItem> foods = [
    FoodItem(
      id: 'f1',
      restaurantId: 'r1',
      name: 'Special Chicken Dum Biryani',
      description: 'Fragrant aged basmati rice slow-cooked with spiced chicken and saffron.',
      image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
      price: 480.0,
      category: 'Biryani',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Extra Raita', 'Fresh Salad', 'Boiled Egg', 'Double Chicken Piece'],
    ),
    FoodItem(
      id: 'f2',
      restaurantId: 'r1',
      name: 'Beef Yakhni Pulao',
      description: 'Tender beef shank cuts infused with aromatic whole spice stock and basmati rice.',
      image: 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?auto=format&fit=crop&w=600&q=80',
      price: 590.0,
      category: 'Biryani',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Mint Chutney', 'Kachumber Salad', 'Shami Kabab'],
    ),
    FoodItem(
      id: 'f3',
      restaurantId: 'r1',
      name: 'Zaffrani Mutton Biryani',
      description: 'Royal mutton dum biryani layered with golden caramelized onions and saffron milk.',
      image: 'https://images.unsplash.com/photo-1545247181-516773cae7be?auto=format&fit=crop&w=600&q=80',
      price: 890.0,
      category: 'Biryani',
      rating: 4.9,
      popular: false,
      available: true,
      reviewCount: 160,
      addOns: ['Zeera Raita', 'Extra Mutton Boti'],
    ),
    FoodItem(
      id: 'f4',
      restaurantId: 'r1',
      name: 'Shami Kabab (2 Pcs)',
      description: 'Pan-fried melt-in-mouth beef and lentils patties with herbs and green chilies.',
      image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80',
      price: 220.0,
      category: 'Snacks',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Green Chutney'],
    ),
    FoodItem(
      id: 'f5',
      restaurantId: 'r1',
      name: 'Chilled Mint Lemonade',
      description: 'Freshly blended garden mint, fresh lemon juice, black salt, and crushed ice.',
      image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
      price: 180.0,
      category: 'Drinks',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Extra Lemon'],
    ),
    FoodItem(
      id: 'f6',
      restaurantId: 'r2',
      name: 'Charcoal Chicken Tikka',
      description: 'Quarter chicken marinated in red tandoori spices and grilled over live charcoal.',
      image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=600&q=80',
      price: 420.0,
      category: 'BBQ',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Roghani Naan', 'Mint Sauce', 'Extra Lemon'],
    ),
    FoodItem(
      id: 'f7',
      restaurantId: 'r2',
      name: 'Melted Reshmi Kabab (4 Pcs)',
      description: 'Ultra tender minced chicken kababs seasoned with cream, roasted cumin, and coriander.',
      image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=600&q=80',
      price: 650.0,
      category: 'BBQ',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Garlic Mayo', 'Kandhari Naan'],
    ),
    FoodItem(
      id: 'f8',
      restaurantId: 'r2',
      name: 'Smokey Malai Boti',
      description: 'Boneless chicken cubes marinated in green chili, fresh cream, and grilled to butteriness.',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?auto=format&fit=crop&w=600&q=80',
      price: 690.0,
      category: 'BBQ',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Plum Chutney', 'Butter Paratha'],
    ),
    FoodItem(
      id: 'f9',
      restaurantId: 'r2',
      name: 'Sultani Special Mixed BBQ Platter',
      description: 'Tikka piece, 2 seekh kababs, 4 malai boti, 2 parathas, raita, and fresh salad.',
      image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=600&q=80',
      price: 1550.0,
      category: 'BBQ',
      rating: 5.0,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Extra Paratha', 'Soft Drink 1.5L'],
    ),
    FoodItem(
      id: 'f10',
      restaurantId: 'r2',
      name: 'Fresh Tandoori Roghani Naan',
      description: 'Fluffy tandoori bread topped with sesame seeds and brushed with melted desi butter.',
      image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80',
      price: 80.0,
      category: 'Pakistani',
      rating: 4.7,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Garlic Butter'],
    ),
    FoodItem(
      id: 'f11',
      restaurantId: 'r3',
      name: 'Double Smashed Beef Burger',
      description: 'Two 100% prime beef smashed patties, double American cheese, caramelized onions, brioche bun.',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
      price: 790.0,
      category: 'Burgers',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Extra Beef Patty', 'Crispy Bacon (Halal)', 'Jalapenos', 'Truffle Mayo'],
    ),
    FoodItem(
      id: 'f12',
      restaurantId: 'r3',
      name: 'Crispy Mega Zinger Burger',
      description: 'Buttermilk marinated crispy chicken thigh, iceberg lettuce, tangy secret sauce, sesame bun.',
      image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=600&q=80',
      price: 580.0,
      category: 'Burgers',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Extra Cheese Slice', 'Spicy Dip', 'Coleslaw'],
    ),
    FoodItem(
      id: 'f13',
      restaurantId: 'r3',
      name: 'Loaded Cheddar Curly Fries',
      description: 'Spiral seasoned fries smothered in melted cheddar, diced beef bits, and jalapenos.',
      image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=600&q=80',
      price: 420.0,
      category: 'Fast Food',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Garlic Mayo', 'Extra Melted Cheese'],
    ),
    FoodItem(
      id: 'f14',
      restaurantId: 'r3',
      name: 'Chocolate Fudge Thickshake',
      description: 'Rich blended dairy ice cream, Belgian chocolate syrup, whipped cream, and chocolate curls.',
      image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80',
      price: 380.0,
      category: 'Drinks',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Oreo Crumbs', 'Nutella Swirl'],
    ),
    FoodItem(
      id: 'f15',
      restaurantId: 'r4',
      name: 'Smokey Fajita Stuffed Crust Pizza',
      description: 'Spiced chicken fajita strips, bell peppers, onions, stuffed mozzarella crust, herb sauce.',
      image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
      price: 1350.0,
      category: 'Pizza',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Extra Cheese', 'Black Olives', 'Mushrooms', 'Garlic Ranch Dip'],
    ),
    FoodItem(
      id: 'f16',
      restaurantId: 'r4',
      name: 'Chicken Tikka Supreme Pizza',
      description: 'Charcoal tikka pieces, sweet corn, red onion, jalapeño rings, and rich mozzarella.',
      image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=600&q=80',
      price: 1250.0,
      category: 'Pizza',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Extra Toppings', 'Spicy Mayo Dip'],
    ),
    FoodItem(
      id: 'f17',
      restaurantId: 'r4',
      name: 'Cheesy Garlic Bread Sticks (6 Pcs)',
      description: 'Freshly baked pull-apart breadsticks brushed with herb garlic butter and parmesan.',
      image: 'https://images.unsplash.com/photo-1619895092538-128341789043?auto=format&fit=crop&w=600&q=80',
      price: 380.0,
      category: 'Snacks',
      rating: 4.7,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Marinara Sauce', 'Cheddar Dip'],
    ),
    FoodItem(
      id: 'f18',
      restaurantId: 'r4',
      name: 'Classic Pepperoni Passion Pizza',
      description: 'Loaded halal beef pepperoni slices on crushed San Marzano tomato sauce and mozzarella.',
      image: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?auto=format&fit=crop&w=600&q=80',
      price: 1400.0,
      category: 'Pizza',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Chili Flakes', 'Hot Honey Drizzle'],
    ),
    FoodItem(
      id: 'f19',
      restaurantId: 'r5',
      name: 'Arabic Jumbo Chicken Shawarma',
      description: 'Marinated shaved rotisserie chicken, garlic toum, salty pickles, wrapped in Syrian saj bread.',
      image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=600&q=80',
      price: 340.0,
      category: 'Shawarma',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Extra Garlic Sauce', 'Cheese Slice', 'French Fries Inside'],
    ),
    FoodItem(
      id: 'f20',
      restaurantId: 'r5',
      name: 'Crispy Quarter Broast (Chest Piece)',
      description: 'Crunchy skin deep-fried chicken piece served with fries, garlic dip, and soft dinner roll.',
      image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80',
      price: 460.0,
      category: 'Fast Food',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Extra Dinner Roll', 'Spicy Garlic Dip'],
    ),
    FoodItem(
      id: 'f21',
      restaurantId: 'r5',
      name: 'Open Shawarma Rice Platter',
      description: 'Fragrant spiced yellow rice topped with sliced shawarma chicken, garlic tahini, and pita crisps.',
      image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
      price: 520.0,
      category: 'Shawarma',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Hot Chili Sauce', 'Extra Pickles'],
    ),
    FoodItem(
      id: 'f21b',
      restaurantId: 'r5',
      name: 'Cheesy Chicken Shawarma Roll',
      description: 'Toasted flatbread filled with shredded rotisserie chicken and melted cheddar mozzarella blend.',
      image: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&w=600&q=80',
      price: 390.0,
      category: 'Shawarma',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Jalapenos', 'Garlic Mayo'],
    ),
    FoodItem(
      id: 'f22',
      restaurantId: 'r6',
      name: 'Chicken Manchurian & Egg Fried Rice',
      description: 'Diced chicken in sweet and spicy red gravy served with wok-tossed egg scallion rice.',
      image: 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=600&q=80',
      price: 720.0,
      category: 'Chinese',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Extra Gravy', 'Chili Vinegar', 'Prawn Crackers'],
    ),
    FoodItem(
      id: 'f23',
      restaurantId: 'r6',
      name: 'Kung Pao Chicken (Spicy)',
      description: 'Wok-seared chicken with roasted whole peanuts, dry red chilies, and scallions in soy sauce.',
      image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=600&q=80',
      price: 790.0,
      category: 'Chinese',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Egg Fried Rice', 'Steamed Rice'],
    ),
    FoodItem(
      id: 'f24',
      restaurantId: 'r6',
      name: 'Special Chicken Chow Mein',
      description: 'Pan-fried egg noodles with shredded chicken, cabbage, carrots, and aromatic sesame oil.',
      image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80',
      price: 650.0,
      category: 'Chinese',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Hot Sauce', 'Spring Rolls (2 Pcs)'],
    ),
    FoodItem(
      id: 'f24b',
      restaurantId: 'r6',
      name: 'Golden Fried Chicken Spring Rolls (4 Pcs)',
      description: 'Crispy golden rolls packed with seasoned chicken and crunchy garden vegetables.',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?auto=format&fit=crop&w=600&q=80',
      price: 380.0,
      category: 'Snacks',
      rating: 4.6,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Sweet & Sour Dip'],
    ),
    FoodItem(
      id: 'f25',
      restaurantId: 'r7',
      name: '4 Pcs Crispy Chicken Bucket',
      description: 'Four pieces of golden crunch fried chicken with 2 dinner rolls and garlic dip.',
      image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80',
      price: 790.0,
      category: 'Fast Food',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Coleslaw', 'Large Fries', 'Chili Garlic Dip'],
    ),
    FoodItem(
      id: 'f26',
      restaurantId: 'r7',
      name: 'Spicy Popcorn Chicken Nuggets (12 Pcs)',
      description: 'Bite-sized tender chicken breast pieces in seasoned crispy batter with honey mustard dip.',
      image: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80',
      price: 390.0,
      category: 'Fast Food',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Honey Mustard Dip', 'Spicy Mayo'],
    ),
    FoodItem(
      id: 'f27',
      restaurantId: 'r7',
      name: 'The Giant Crispy Submarine Sandwich',
      description: 'Footlong toasted bun packed with crispy chicken strips, sliced cheese, lettuce, and chipotle sauce.',
      image: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=600&q=80',
      price: 640.0,
      category: 'Fast Food',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Extra Cheese', 'Jalapenos'],
    ),
    FoodItem(
      id: 'f27b',
      restaurantId: 'r7',
      name: 'Cheesy Seasoned Crinkle Fries',
      description: 'Crispy crinkle-cut potato fries dusted with peri-peri spice and cheddar cheese sauce.',
      image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=600&q=80',
      price: 320.0,
      category: 'Snacks',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Extra Cheese Sauce'],
    ),
    FoodItem(
      id: 'f28',
      restaurantId: 'r8',
      name: 'Karak Doodh Patti Matka Chai',
      description: 'Slow-simmered rich creamy tea brewed with cardamom and organic saffron in a clay cup.',
      image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=600&q=80',
      price: 140.0,
      category: 'Tea/Coffee',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Extra Cardamom', 'Gur (Jaggery)'],
    ),
    FoodItem(
      id: 'f29',
      restaurantId: 'r8',
      name: 'Stuffed Aloo Cheese Paratha',
      description: 'Crispy golden layered paratha stuffed with seasoned mashed potatoes, mozzarella, and green chilies.',
      image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80',
      price: 260.0,
      category: 'Breakfast',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Desi Makhan (Butter)', 'Mint Raita', 'Achar'],
    ),
    FoodItem(
      id: 'f30',
      restaurantId: 'r8',
      name: 'Triple Decker Cafe Club Sandwich',
      description: 'Grilled chicken, fried egg, cheddar slice, tomatoes, lettuce, served with golden crinkle fries.',
      image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=600&q=80',
      price: 480.0,
      category: 'Fast Food',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Extra Coleslaw', 'Garlic Mayo'],
    ),
    FoodItem(
      id: 'f30b',
      restaurantId: 'r8',
      name: 'Kashmiri Pink Tea (Gulabi Chai)',
      description: 'Traditional brewed green tea leaves with milk, crushed pistachios, and almonds.',
      image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
      price: 200.0,
      category: 'Tea/Coffee',
      rating: 4.9,
      popular: false,
      available: true,
      reviewCount: 160,
      addOns: ['Extra Dry Fruits'],
    ),
    FoodItem(
      id: 'f31',
      restaurantId: 'r9',
      name: 'Original Bahawalpur Sohan Halwa (500g)',
      description: 'Legendary rich dark caramelized sweet halwa loaded with roasted almonds, pistachios, and walnuts.',
      image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80',
      price: 650.0,
      category: 'Bakery',
      rating: 5.0,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Gift Box Packaging', 'Extra Dry Fruits'],
    ),
    FoodItem(
      id: 'f32',
      restaurantId: 'r9',
      name: 'Gulab Jamun Warm Box (6 Pcs)',
      description: 'Soft khoya dumplings soaked in fragrant cardamom and rose water sugar syrup.',
      image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
      price: 340.0,
      category: 'Desserts',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Silver Warq', 'Pistachio Topping'],
    ),
    FoodItem(
      id: 'f33',
      restaurantId: 'r9',
      name: 'Fresh Baked Chicken Patties (4 Pcs)',
      description: 'Flaky golden puff pastries generously stuffed with seasoned shredded chicken and black pepper.',
      image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
      price: 360.0,
      category: 'Bakery',
      rating: 4.7,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Chili Tomato Sauce'],
    ),
    FoodItem(
      id: 'f33b',
      restaurantId: 'r9',
      name: 'Premium Almond Dry Cake',
      description: 'Moist butter sponge cake encrusted with crunchy roasted almond flakes.',
      image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80',
      price: 420.0,
      category: 'Bakery',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Gift Wrapping'],
    ),
    FoodItem(
      id: 'f34',
      restaurantId: 'r10',
      name: 'Molten Lava Cake with Vanilla Gelato',
      description: 'Warm dark chocolate sponge oozing with molten fudge, paired with a scoop of Madagascar vanilla gelato.',
      image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=600&q=80',
      price: 520.0,
      category: 'Desserts',
      rating: 5.0,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Double Scoop Gelato', 'Caramel Drizzle'],
    ),
    FoodItem(
      id: 'f35',
      restaurantId: 'r10',
      name: 'Nutella & Banana Loaded Waffle',
      description: 'Crisp golden Belgian waffle smothered in authentic Nutella, sliced bananas, and crushed hazelnuts.',
      image: 'https://images.unsplash.com/photo-1562376552-0d160a2f238d?auto=format&fit=crop&w=600&q=80',
      price: 580.0,
      category: 'Desserts',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Whipped Cream', 'Lotus Biscoff Spread'],
    ),
    FoodItem(
      id: 'f36',
      restaurantId: 'r10',
      name: 'Lotus Biscoff Thick Shake',
      description: 'Rich creamy shake blended with real Lotus biscuits, caramel sauce, and cookie crumb rim.',
      image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80',
      price: 460.0,
      category: 'Drinks',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Extra Biscoff Sauce'],
    ),
    FoodItem(
      id: 'f36b',
      restaurantId: 'r10',
      name: 'Artisan Double Scoop Gelato Tub',
      description: 'Choice of two scoops: Pistachio Crunch, Belgian Chocolate, Mango Alphonso, or Wild Berry.',
      image: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?auto=format&fit=crop&w=600&q=80',
      price: 400.0,
      category: 'Desserts',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Waffle Cone', 'Sprinkles'],
    ),
    FoodItem(
      id: 'f37',
      restaurantId: 'r11',
      name: 'Grilled Chicken Protein Salad Bowl',
      description: 'Herb grilled chicken breast, fresh baby greens, cucumbers, cherry tomatoes, and citrus vinaigrette.',
      image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80',
      price: 620.0,
      category: 'Healthy',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Boiled Egg', 'Extra Grilled Chicken', 'Feta Cheese'],
    ),
    FoodItem(
      id: 'f38',
      restaurantId: 'r11',
      name: 'ABC Detox Cold-Pressed Juice',
      description: 'Freshly extracted apple, beetroot, and carrot juice with a hint of ginger and lemon.',
      image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=600&q=80',
      price: 320.0,
      category: 'Drinks',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Chia Seeds', 'No Ice'],
    ),
    FoodItem(
      id: 'f38b',
      restaurantId: 'r11',
      name: 'Quinoa Avocado Crunch Bowl',
      description: 'Steamed organic quinoa, diced hass avocado, sweet corn, black beans, and lime dressing.',
      image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
      price: 680.0,
      category: 'Healthy',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Grilled Halloumi', 'Walnuts'],
    ),
    FoodItem(
      id: 'f38c',
      restaurantId: 'r11',
      name: 'Green Vitality Spinach Detox Smoothie',
      description: 'Fresh baby spinach, green apple, cucumber, mint, and pure coconut water.',
      image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=600&q=80',
      price: 350.0,
      category: 'Drinks',
      rating: 4.7,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Flax Seeds'],
    ),
    FoodItem(
      id: 'f39',
      restaurantId: 'r12',
      name: 'Traditional Halwa Puri Nashta Thali',
      description: '3 hot puffed puris, spicy Lahori chana masala, sweet sooji halwa, and tangy mango pickle.',
      image: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=600&q=80',
      price: 350.0,
      category: 'Breakfast',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Extra Puri (1 Pc)', 'Achar', 'Sweet Lassi'],
    ),
    FoodItem(
      id: 'f40',
      restaurantId: 'r12',
      name: 'Thick Sweet Malai Lassi (500ml)',
      description: 'Churned buffalo yogurt blended with crushed ice and topped with a thick dollop of fresh clotted malai.',
      image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=600&q=80',
      price: 220.0,
      category: 'Drinks',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Almond Flakes', 'Rooh Afza Flavor'],
    ),
    FoodItem(
      id: 'f40b',
      restaurantId: 'r12',
      name: 'Desi Ghee Meetha Pura & Omelette',
      description: 'Sweet wholewheat pancake cooked in desi ghee paired with 2-egg spicy green chili omelette.',
      image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80',
      price: 320.0,
      category: 'Breakfast',
      rating: 4.7,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Extra Egg', 'Desi Chai'],
    ),
    FoodItem(
      id: 'f40c',
      restaurantId: 'r12',
      name: 'Crispy Lachha Paratha',
      description: 'Golden multi-layered pan-fried paratha with flaky rings and buttery aroma.',
      image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80',
      price: 90.0,
      category: 'Breakfast',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Butter Slice'],
    ),
    FoodItem(
      id: 'f41',
      restaurantId: 'r13',
      name: 'Ghar Ka Daal Chawal & Shami Thali',
      description: 'Comforting yellow lentils tadka with cumin and garlic, steamed basmati rice, beef shami, and salad.',
      image: 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?auto=format&fit=crop&w=600&q=80',
      price: 420.0,
      category: 'Home Kitchen',
      rating: 5.0,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Desi Ghee Spoon', 'Extra Shami Kabab', 'Mint Raita'],
    ),
    FoodItem(
      id: 'f42',
      restaurantId: 'r13',
      name: 'Homestyle Chicken Palak Curry',
      description: 'Fresh spinach pureed with garlic and green chilies, simmered with tender chicken drumsticks.',
      image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80',
      price: 580.0,
      category: 'Home Kitchen',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Tawa Roti (2 Pcs)', 'Desi Butter'],
    ),
    FoodItem(
      id: 'f43',
      restaurantId: 'r13',
      name: 'Aloo Keema Masaledar',
      description: 'Minced beef slow cooked with tender potato cubes, whole spices, ginger juliennes, and cilantro.',
      image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80',
      price: 620.0,
      category: 'Home Kitchen',
      rating: 4.9,
      popular: false,
      available: true,
      reviewCount: 160,
      addOns: ['Hot Roti', 'Lemon Wedges'],
    ),
    FoodItem(
      id: 'f43b',
      restaurantId: 'r13',
      name: 'Fresh Tawa Phulka (3 Pcs)',
      description: 'Soft homestyle whole wheat rotis baked on tawa with no oil, light and easy to digest.',
      image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80',
      price: 75.0,
      category: 'Home Kitchen',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Desi Ghee Brush'],
    ),
    FoodItem(
      id: 'f44',
      restaurantId: 'r14',
      name: 'Special Shinwari Chicken Karahi (1 KG)',
      description: 'Cooked in fresh animal fat, ripe juicy tomatoes, coarse black pepper, and whole green chilies.',
      image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80',
      price: 1650.0,
      category: 'Pakistani',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Extra Butter', 'Ginger Garnish', 'Garlic Naan (2 Pcs)'],
    ),
    FoodItem(
      id: 'f45',
      restaurantId: 'r14',
      name: 'Shinwari Mutton Karahi (Half KG)',
      description: 'Tender mountain mutton cuts cooked without spices except sea salt and crushed black pepper.',
      image: 'https://images.unsplash.com/photo-1545247181-516773cae7be?auto=format&fit=crop&w=600&q=80',
      price: 1850.0,
      category: 'Pakistani',
      rating: 5.0,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Roghani Naan', 'Zeera Raita'],
    ),
    FoodItem(
      id: 'f45b',
      restaurantId: 'r14',
      name: 'Shinwari Tikka Karahi Half Chicken',
      description: 'Charcoal grilled tikka pieces finished in simmering tomato butter gravy.',
      image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=600&q=80',
      price: 950.0,
      category: 'Pakistani',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Butter Naan'],
    ),
    FoodItem(
      id: 'f45c',
      restaurantId: 'r14',
      name: 'Hot Garlic Tandoori Naan',
      description: 'Tandoor baked bread encrusted with minced roasted garlic and fresh coriander.',
      image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80',
      price: 90.0,
      category: 'Pakistani',
      rating: 4.7,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Sesame Seeds'],
    ),
    FoodItem(
      id: 'f46',
      restaurantId: 'r15',
      name: 'Spicy Student Special Chicken Biryani',
      description: 'Tangy plum and whole spiced chicken biryani with soft yellow potato and pickled onions.',
      image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
      price: 420.0,
      category: 'Biryani',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Double Aloo', 'Extra Chicken Piece', 'Raita'],
    ),
    FoodItem(
      id: 'f47',
      restaurantId: 'r15',
      name: 'Traditional Shahi Zarda',
      description: 'Sweet fragrant yellow basmati rice garnished with raisins, almonds, and tiny rasgullas.',
      image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
      price: 250.0,
      category: 'Desserts',
      rating: 4.6,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Khoya Topping'],
    ),
    FoodItem(
      id: 'f47b',
      restaurantId: 'r15',
      name: 'Single Chicken Biryani (Economical)',
      description: 'Full plate spicy rice with one tender chicken piece and spiced aloo.',
      image: 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?auto=format&fit=crop&w=600&q=80',
      price: 340.0,
      category: 'Biryani',
      rating: 4.6,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Cold Drink 345ml'],
    ),
    FoodItem(
      id: 'f47c',
      restaurantId: 'r15',
      name: 'Cucumber Mint Raita',
      description: 'Chilled spiced whipped curd with diced fresh cucumbers and roasted cumin.',
      image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
      price: 70.0,
      category: 'Snacks',
      rating: 4.5,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Boondi'],
    ),
    FoodItem(
      id: 'f48',
      restaurantId: 'r16',
      name: 'Beef Gola Kabab Plate (6 Pcs)',
      description: 'Spherical smoked beef kababs infused with raw papaya, nutmeg, and mace.',
      image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=600&q=80',
      price: 580.0,
      category: 'BBQ',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Onion Rings', 'Pudina Chutney', 'Paratha'],
    ),
    FoodItem(
      id: 'f49',
      restaurantId: 'r16',
      name: 'Chicken Hariyali Boti',
      description: 'Boneless chicken cubes coated in fresh coriander, mint, green chilies, and yogurt paste.',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?auto=format&fit=crop&w=600&q=80',
      price: 620.0,
      category: 'BBQ',
      rating: 4.7,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Roghani Naan'],
    ),
    FoodItem(
      id: 'f49b',
      restaurantId: 'r16',
      name: 'Mutton Seekh Kabab (4 Pcs)',
      description: 'Hand-chopped spiced minced mutton threaded on wide skewers and grilled over hot coals.',
      image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=600&q=80',
      price: 890.0,
      category: 'BBQ',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Special Salad', 'Plum Dip'],
    ),
    FoodItem(
      id: 'f49c',
      restaurantId: 'r16',
      name: 'Crispy Tandoori Paratha',
      description: 'Layered crisp flatbread baked inside tandoor with brushing of desi ghee.',
      image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80',
      price: 110.0,
      category: 'Pakistani',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Extra Butter'],
    ),
    FoodItem(
      id: 'f50',
      restaurantId: 'r17',
      name: 'Jalapeno Cheddar Beef Burger',
      description: 'Charbroiled beef patty with pickled fiery jalapenos, sharp cheddar sauce, and chipotle mayo.',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
      price: 720.0,
      category: 'Burgers',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Extra Jalapenos', 'Onion Rings'],
    ),
    FoodItem(
      id: 'f51',
      restaurantId: 'r17',
      name: 'Crispy Buffalo Chicken Burger',
      description: 'Fried chicken tossed in tangy spicy buffalo glaze, iceberg lettuce, and blue cheese dressing.',
      image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=600&q=80',
      price: 630.0,
      category: 'Burgers',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Cheddar Slice', 'Fries'],
    ),
    FoodItem(
      id: 'f51b',
      restaurantId: 'r17',
      name: 'Smokey BBQ Bacon Beef Burger',
      description: 'Beef patty smothered in hickory barbecue glaze, crispy strips, and caramelized shallots.',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
      price: 760.0,
      category: 'Burgers',
      rating: 4.9,
      popular: false,
      available: true,
      reviewCount: 160,
      addOns: ['Double Cheese', 'Fried Egg'],
    ),
    FoodItem(
      id: 'f51c',
      restaurantId: 'r17',
      name: 'Crispy Golden Onion Rings (8 Pcs)',
      description: 'Thick cut sweet onion rings dipped in panko breadcrumbs and fried golden.',
      image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80',
      price: 290.0,
      category: 'Snacks',
      rating: 4.6,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Ranch Dip'],
    ),
    FoodItem(
      id: 'f52',
      restaurantId: 'r18',
      name: 'Margherita DOC Wood-Fired Pizza',
      description: 'San Marzano tomatoes, fresh buffalo mozzarella, fresh basil leaves, extra virgin olive oil.',
      image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=600&q=80',
      price: 1190.0,
      category: 'Pizza',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Extra Buffalo Mozzarella', 'Hot Chili Flakes'],
    ),
    FoodItem(
      id: 'f53',
      restaurantId: 'r18',
      name: 'Four Cheese Formaggi Pizza',
      description: 'Decadent blend of mozzarella, gorgonzola, parmesan, and ricotta on stone-baked crust.',
      image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
      price: 1450.0,
      category: 'Pizza',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Truffle Oil Drizzle'],
    ),
    FoodItem(
      id: 'f53b',
      restaurantId: 'r18',
      name: 'Spicy Salami & Hot Honey Pizza',
      description: 'Thin crust with sliced halal beef salami, fiery jalapeños, and organic hot honey swirl.',
      image: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?auto=format&fit=crop&w=600&q=80',
      price: 1490.0,
      category: 'Pizza',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Extra Honey Dip'],
    ),
    FoodItem(
      id: 'f53c',
      restaurantId: 'r18',
      name: 'Tiramisu Classic Slice',
      description: 'Espresso dipped ladyfingers layered with whipped mascarpone cream and dusted Dutch cocoa.',
      image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=600&q=80',
      price: 480.0,
      category: 'Desserts',
      rating: 4.9,
      popular: false,
      available: true,
      reviewCount: 160,
      addOns: ['Extra Cocoa Powder'],
    ),
    FoodItem(
      id: 'f54',
      restaurantId: 'r19',
      name: 'Damascus Special Falafel Pocket',
      description: 'Freshly fried herbed chickpea patties, cucumber tomato salad, creamy tahini, in warm pita.',
      image: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&w=600&q=80',
      price: 290.0,
      category: 'Shawarma',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Extra Tahini', 'Hummus Dip'],
    ),
    FoodItem(
      id: 'f55',
      restaurantId: 'r19',
      name: 'Creamy Hummus & Olive Oil Dip with Pita',
      description: 'Silky blended chickpeas with roasted sesame tahini, olive oil, and 2 fresh warm pita breads.',
      image: 'https://images.unsplash.com/photo-1577906096429-f73c2c312435?auto=format&fit=crop&w=600&q=80',
      price: 380.0,
      category: 'Snacks',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Extra Pita Bread (2 Pcs)'],
    ),
    FoodItem(
      id: 'f55b',
      restaurantId: 'r19',
      name: 'Damascus Chicken Shish Tawook Platter',
      description: 'Skewered chicken breast marinated in yogurt and garlic, grilled and served with garlic toum.',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?auto=format&fit=crop&w=600&q=80',
      price: 720.0,
      category: 'Shawarma',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Fries', 'Pickled Turnips'],
    ),
    FoodItem(
      id: 'f55c',
      restaurantId: 'r19',
      name: 'Mint Ayran Chilled Yogurt Drink',
      description: 'Traditional refreshing savory salty yogurt beverage whipped with crushed dried mint.',
      image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
      price: 160.0,
      category: 'Drinks',
      rating: 4.6,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Ice Cubes'],
    ),
    FoodItem(
      id: 'f56',
      restaurantId: 'r20',
      name: 'Steamed Chicken Dumplings (6 Pcs)',
      description: 'Delicate steamed wontons filled with minced scallion chicken, served with spicy chili oil dip.',
      image: 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?auto=format&fit=crop&w=600&q=80',
      price: 480.0,
      category: 'Chinese',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Chili Crisp Oil', 'Sweet Soy Dip'],
    ),
    FoodItem(
      id: 'f57',
      restaurantId: 'r20',
      name: 'Crispy Szechuan Dry Beef',
      description: 'Shredded beef strips wok-fried with bell peppers, toasted sesame, and tongue-tingling chili oil.',
      image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=600&q=80',
      price: 850.0,
      category: 'Chinese',
      rating: 4.7,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Egg Fried Rice'],
    ),
    FoodItem(
      id: 'f57b',
      restaurantId: 'r20',
      name: 'Hot & Sour Soup (Bowl)',
      description: 'Thick peppery broth loaded with shredded chicken, black mushrooms, tofu, and bamboo shoots.',
      image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=600&q=80',
      price: 380.0,
      category: 'Chinese',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Crispy Wonton Chips', 'Vinegar Dip'],
    ),
    FoodItem(
      id: 'f57c',
      restaurantId: 'r20',
      name: 'Garlic Chili Chicken with Scallions',
      description: 'Boneless chicken cubes tossed with golden fried garlic chunks, dark soy, and Thai chilies.',
      image: 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=600&q=80',
      price: 780.0,
      category: 'Chinese',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Vegetable Fried Rice'],
    ),
    FoodItem(
      id: 'f58',
      restaurantId: 'r21',
      name: 'Cheesy Pizza Fries Platter',
      description: 'Bed of golden french fries layered with pizza sauce, mozzarella cheese, and chicken tikka chunks.',
      image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=600&q=80',
      price: 450.0,
      category: 'Fast Food',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Jalapenos', 'Black Olives', 'Extra Cheese'],
    ),
    FoodItem(
      id: 'f59',
      restaurantId: 'r21',
      name: 'Crispy Chicken Strips (5 Pcs)',
      description: 'Whole chicken breast strips coated in spiced crumb coating with sweet honey barbecue dip.',
      image: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80',
      price: 380.0,
      category: 'Fast Food',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Honey BBQ Sauce', 'Garlic Ranch'],
    ),
    FoodItem(
      id: 'f59b',
      restaurantId: 'r21',
      name: 'Loaded Chapli Burger Supreme',
      description: 'Traditional spiced Peshawar style beef chapli patty, fried egg, sliced tomatoes, mint mayo.',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
      price: 460.0,
      category: 'Burgers',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Extra Chapli Patty', 'Cheddar Slice'],
    ),
    FoodItem(
      id: 'f59c',
      restaurantId: 'r21',
      name: 'Blue Lagoon Mint Chiller',
      description: 'Sparkling citrus soda infused with blue curacao syrup, crushed ice, and fresh mint sprigs.',
      image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
      price: 220.0,
      category: 'Drinks',
      rating: 4.6,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Lemon Slice'],
    ),
    FoodItem(
      id: 'f60',
      restaurantId: 'r22',
      name: 'Spanish Iced Caramel Latte',
      description: 'Double shot of freshly ground espresso poured over cold sweet condensed milk and caramel drizzle.',
      image: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=600&q=80',
      price: 420.0,
      category: 'Tea/Coffee',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Oat Milk Option', 'Extra Espresso Shot', 'Vanilla Syrup'],
    ),
    FoodItem(
      id: 'f61',
      restaurantId: 'r22',
      name: 'French Butter Croissant',
      description: 'Multi-layered flaky buttery pastry baked fresh daily with golden crisp exterior.',
      image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=600&q=80',
      price: 280.0,
      category: 'Bakery',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Nutella Spread', 'Strawberry Jam'],
    ),
    FoodItem(
      id: 'f61b',
      restaurantId: 'r22',
      name: 'Hot Cappuccino with Cinnamon Dust',
      description: 'Equal parts rich espresso, steamed milk, and velvety foam with a sprinkle of Ceylon cinnamon.',
      image: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&w=600&q=80',
      price: 360.0,
      category: 'Tea/Coffee',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Hazelnut Syrup', 'Caramel Drizzle'],
    ),
    FoodItem(
      id: 'f61c',
      restaurantId: 'r22',
      name: 'Fudge Brownie with Espresso Ganache',
      description: 'Dense dark chocolate walnut brownie smothered in warm coffee chocolate glaze.',
      image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=600&q=80',
      price: 320.0,
      category: 'Desserts',
      rating: 4.9,
      popular: false,
      available: true,
      reviewCount: 160,
      addOns: ['Vanilla Scoop'],
    ),
    FoodItem(
      id: 'f62',
      restaurantId: 'r23',
      name: 'New York Baked Cheesecake Slice',
      description: 'Dense and velvety cream cheese filling on buttery graham cracker crust with strawberry coulis.',
      image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=600&q=80',
      price: 490.0,
      category: 'Desserts',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Extra Strawberry Coulis', 'Whipped Cream'],
    ),
    FoodItem(
      id: 'f63',
      restaurantId: 'r23',
      name: 'Rich Red Velvet Cupcake',
      description: 'Moist cocoa buttermilk cake crowned with swirl of authentic cream cheese frosting.',
      image: 'https://images.unsplash.com/photo-1587668178277-295251f900ce?auto=format&fit=crop&w=600&q=80',
      price: 220.0,
      category: 'Bakery',
      rating: 4.7,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Decorative Topping'],
    ),
    FoodItem(
      id: 'f63b',
      restaurantId: 'r23',
      name: 'Lotus Biscoff Cheesecake Tart',
      description: 'Miniature tart filled with caramelized Lotus cream and topped with whole speculoos biscuit.',
      image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80',
      price: 450.0,
      category: 'Desserts',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Gold Leaf Topping'],
    ),
    FoodItem(
      id: 'f63c',
      restaurantId: 'r23',
      name: 'Spicy Chicken Puff Roll (2 Pcs)',
      description: 'Rolled golden puff pastry encasing spiced chicken sausage and mozzarella cheese.',
      image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
      price: 280.0,
      category: 'Bakery',
      rating: 4.6,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Chili Garlic Sauce'],
    ),
    FoodItem(
      id: 'f64',
      restaurantId: 'r24',
      name: 'Lemon Herb Grilled Chicken Breast',
      description: '250g grilled chicken served with steamed broccoli, roasted sweet potatoes, and herb yogurt dip.',
      image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
      price: 690.0,
      category: 'Healthy',
      rating: 4.8,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Avocado Slices', 'Extra Steamed Veggies'],
    ),
    FoodItem(
      id: 'f65',
      restaurantId: 'r24',
      name: 'Banana Berry Protein Smoothie',
      description: 'Unsweetened almond milk, ripe bananas, wild berries, and 25g plant whey protein.',
      image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=600&q=80',
      price: 420.0,
      category: 'Drinks',
      rating: 4.7,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Peanut Butter Scoop', 'Chia Seeds'],
    ),
    FoodItem(
      id: 'f65b',
      restaurantId: 'r24',
      name: 'Mediterranean Falafel Green Salad',
      description: 'Baked herb chickpea falafels on a bed of rocket, kalamata olives, cucumbers, and tahini lemon dressing.',
      image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80',
      price: 580.0,
      category: 'Healthy',
      rating: 4.7,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Extra Tahini', 'Boiled Egg'],
    ),
    FoodItem(
      id: 'f65c',
      restaurantId: 'r24',
      name: 'Cold-Pressed Pomegranate Elixir',
      description: '100% pure fresh ruby red pomegranate juice with no water or sweetener added.',
      image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=600&q=80',
      price: 380.0,
      category: 'Drinks',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['No Ice'],
    ),
    FoodItem(
      id: 'f66',
      restaurantId: 'r25',
      name: 'Creamy Chicken Boneless Handi',
      description: 'Tender boneless chicken simmered in clay pot with heavy dairy cream, crushed coriander, and butter.',
      image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80',
      price: 1250.0,
      category: 'Pakistani',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Extra Cream', 'Garlic Naan', 'Desi Ghee Tadka'],
    ),
    FoodItem(
      id: 'f67',
      restaurantId: 'r25',
      name: 'Mutton Brain Masala (Maghaz)',
      description: 'Delicate mutton brain sautéed with finely chopped onions, tomatoes, and aromatic whole spices.',
      image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80',
      price: 980.0,
      category: 'Pakistani',
      rating: 4.8,
      popular: false,
      available: true,
      reviewCount: 95,
      addOns: ['Roghani Naan', 'Fresh Green Chilies'],
    ),
    FoodItem(
      id: 'f68',
      restaurantId: 'r25',
      name: 'Daal Mash Special Fry',
      description: 'White lentils cooked to firm perfection and fried in desi butter with sliced ginger and whole cumin.',
      image: 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?auto=format&fit=crop&w=600&q=80',
      price: 480.0,
      category: 'Pakistani',
      rating: 4.7,
      popular: true,
      available: true,
      reviewCount: 95,
      addOns: ['Tandoori Roti (2 Pcs)', 'Achar'],
    ),
    FoodItem(
      id: 'f69',
      restaurantId: 'r25',
      name: 'Chicken Reshmi Handi',
      description: 'Silky white sauce chicken handi with cashews, white pepper, and green cardamom.',
      image: 'https://images.unsplash.com/photo-1545247181-516773cae7be?auto=format&fit=crop&w=600&q=80',
      price: 1350.0,
      category: 'Pakistani',
      rating: 4.9,
      popular: true,
      available: true,
      reviewCount: 160,
      addOns: ['Butter Naan', 'Raita'],
    ),
  ];

  static final List<Coupon> coupons = [
    Coupon(
      code: 'WELCOME10',
      discountValue: 10.0,
      isPercentage: true,
      minOrderAmount: 500.0,
      title: '10% OFF Welcome Bonus',
      description: 'Get 10% discount on your first food order across all restaurants in Bahawalpur.',
    ),
    Coupon(
      code: 'FEAST20',
      discountValue: 20.0,
      isPercentage: true,
      minOrderAmount: 1000.0,
      title: '20% OFF Desi & BBQ Feast',
      description: 'Special 20% discount on orders of Rs. 1,000 or more on Desi Handi and BBQ.',
    ),
    Coupon(
      code: 'FREESHIP',
      discountValue: 120.0,
      isPercentage: false,
      minOrderAmount: 600.0,
      title: 'Free Delivery',
      description: 'Enjoy zero delivery fees on orders above Rs. 600 from nearby spots.',
    ),
    Coupon(
      code: 'BIRYANI15',
      discountValue: 15.0,
      isPercentage: true,
      minOrderAmount: 600.0,
      title: '15% OFF Biryani & Rice',
      description: 'Save 15% on all your favorite Dum Biryani and Pulao cravings.',
    ),
    Coupon(
      code: 'FLAT300',
      discountValue: 300.0,
      isPercentage: false,
      minOrderAmount: 1500.0,
      title: 'Rs. 300 FLAT OFF',
      description: 'Save big with Rs. 300 flat reduction on family gatherings and group orders.',
    ),
    Coupon(
      code: 'WEEKEND25',
      discountValue: 25.0,
      isPercentage: true,
      minOrderAmount: 1200.0,
      title: '25% OFF Weekend Special',
      description: 'Exclusive 25% discount for weekend family feasts and party platters.',
    ),
  ];

  static List<Restaurant> getRestaurantsForCategory(String category) {
    if (category == 'All') return List<Restaurant>.from(restaurants);
    final catLower = category.toLowerCase().trim();
    return restaurants.where((r) {
      if (r.cuisine.toLowerCase() == catLower) return true;
      if (r.cuisine.toLowerCase().contains(catLower)) return true;
      return foods.any((f) =>
          f.restaurantId == r.id &&
          (f.category.toLowerCase() == catLower ||
              f.category.toLowerCase().contains(catLower) ||
              f.name.toLowerCase().contains(catLower)));
    }).toList();
  }

  static List<FoodItem> getFoodsForCategory(String category) {
    if (category == 'All') return List<FoodItem>.from(foods);
    final catLower = category.toLowerCase().trim();
    return foods.where((f) =>
        f.category.toLowerCase() == catLower ||
        f.category.toLowerCase().contains(catLower) ||
        f.name.toLowerCase().contains(catLower)).toList();
  }

  static List<FoodItem> getPopularDishes() {
    return foods.where((f) => f.popular).toList();
  }

  static Restaurant? getRestaurantById(String id) {
    try {
      return restaurants.firstWhere((r) => r.id == id);
    } catch (_) {
      return null;
    }
  }

  static List<Restaurant> getPopularRestaurants() {
    return restaurants.where((r) => r.isPopular || r.featured).toList();
  }

  static List<Restaurant> getTopRatedRestaurants() {
    final list = restaurants.where((r) => r.rating >= 4.8).toList();
    list.sort((a, b) => b.rating.compareTo(a.rating));
    return list;
  }

  static List<Restaurant> getFastDeliveryRestaurants() {
    final list = restaurants.where((r) => r.deliveryTime.contains('15') || r.distance <= 1.5).toList();
    list.sort((a, b) => a.distance.compareTo(b.distance));
    return list;
  }

  static List<Restaurant> getDealRestaurants() {
    return restaurants.where((r) => r.offer != null).toList();
  }

  static List<Restaurant> getNearbyRestaurants() {
    final list = List<Restaurant>.from(restaurants);
    list.sort((a, b) => a.distance.compareTo(b.distance));
    return list;
  }

  static List<Restaurant> getRecommendedRestaurants() {
    // Curated diverse selection across different cuisines and areas
    final selectedIds = {'r1', 'r2', 'r4', 'r7', 'r10', 'r13', 'r18', 'r25'};
    return restaurants.where((r) => selectedIds.contains(r.id)).toList();
  }
}

