import '../models/restaurant.dart';
import '../models/food_item.dart';
import '../models/coupon.dart';

class SampleData {
  static final List<String> categories = [
    'All', 'Pizza', 'Burgers', 'Pakistani', 'BBQ', 'Chinese', 'Fast Food', 'Desserts', 'Drinks', 'Breakfast', 'Healthy', 'Snacks'
  ];

  static final List<Restaurant> restaurants = [
    Restaurant(
      id: 'r1',
      name: 'Spice Route',
      image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=500',
      cuisine: 'Pakistani',
      rating: 4.5,
      reviewCount: 150,
      deliveryTime: '20-40 min',
      deliveryFee: 2.99,
      minimumOrder: 10.0,
      distance: 2.5,
      featured: true,
      isOpen: true,
    ),
    Restaurant(
      id: 'r2',
      name: 'Urban Bites',
      image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=500',
      cuisine: 'Fast Food',
      rating: 4.5,
      reviewCount: 150,
      deliveryTime: '20-40 min',
      deliveryFee: 2.99,
      minimumOrder: 10.0,
      distance: 2.5,
      featured: true,
      isOpen: true,
    ),
    Restaurant(
      id: 'r3',
      name: 'Karachi Grill',
      image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=500',
      cuisine: 'BBQ',
      rating: 4.5,
      reviewCount: 150,
      deliveryTime: '20-40 min',
      deliveryFee: 2.99,
      minimumOrder: 10.0,
      distance: 2.5,
      featured: true,
      isOpen: true,
    ),
    Restaurant(
      id: 'r4',
      name: 'The Pizza House',
      image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500',
      cuisine: 'Pizza',
      rating: 4.5,
      reviewCount: 150,
      deliveryTime: '20-40 min',
      deliveryFee: 2.99,
      minimumOrder: 10.0,
      distance: 2.5,
      featured: true,
      isOpen: true,
    ),
    Restaurant(
      id: 'r5',
      name: 'Burger District',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500',
      cuisine: 'Burgers',
      rating: 4.5,
      reviewCount: 150,
      deliveryTime: '20-40 min',
      deliveryFee: 2.99,
      minimumOrder: 10.0,
      distance: 2.5,
      featured: true,
      isOpen: true,
    ),
    Restaurant(
      id: 'r6',
      name: 'Royal BBQ',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?w=500',
      cuisine: 'BBQ',
      rating: 4.5,
      reviewCount: 150,
      deliveryTime: '20-40 min',
      deliveryFee: 2.99,
      minimumOrder: 10.0,
      distance: 2.5,
      featured: true,
      isOpen: true,
    ),
    Restaurant(
      id: 'r7',
      name: 'Desi Kitchen',
      image: 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?w=500',
      cuisine: 'Pakistani',
      rating: 4.5,
      reviewCount: 150,
      deliveryTime: '20-40 min',
      deliveryFee: 2.99,
      minimumOrder: 10.0,
      distance: 2.5,
      featured: true,
      isOpen: true,
    ),
    Restaurant(
      id: 'r8',
      name: 'China Bowl',
      image: 'https://images.unsplash.com/photo-1552611052-33e04de081de?w=500',
      cuisine: 'Chinese',
      rating: 4.5,
      reviewCount: 150,
      deliveryTime: '20-40 min',
      deliveryFee: 2.99,
      minimumOrder: 10.0,
      distance: 2.5,
      featured: true,
      isOpen: true,
    ),
    Restaurant(
      id: 'r9',
      name: 'Sweet Cravings',
      image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=500',
      cuisine: 'Desserts',
      rating: 4.5,
      reviewCount: 150,
      deliveryTime: '20-40 min',
      deliveryFee: 2.99,
      minimumOrder: 10.0,
      distance: 2.5,
      featured: true,
      isOpen: true,
    ),
    Restaurant(
      id: 'r10',
      name: 'Street Food Co.',
      image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=500',
      cuisine: 'Snacks',
      rating: 4.5,
      reviewCount: 150,
      deliveryTime: '20-40 min',
      deliveryFee: 2.99,
      minimumOrder: 10.0,
      distance: 2.5,
      featured: true,
      isOpen: true,
    ),
    Restaurant(
      id: 'r11',
      name: 'Green Garden',
      image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500',
      cuisine: 'Healthy',
      rating: 4.5,
      reviewCount: 150,
      deliveryTime: '20-40 min',
      deliveryFee: 2.99,
      minimumOrder: 10.0,
      distance: 2.5,
      featured: true,
      isOpen: true,
    ),
    Restaurant(
      id: 'r12',
      name: 'Coffee & Co.',
      image: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=500',
      cuisine: 'Drinks',
      rating: 4.5,
      reviewCount: 150,
      deliveryTime: '20-40 min',
      deliveryFee: 2.99,
      minimumOrder: 10.0,
      distance: 2.5,
      featured: true,
      isOpen: true,
    ),
    Restaurant(
      id: 'r13',
      name: 'Food Junction',
      image: 'https://images.unsplash.com/photo-1610440042657-612c34d95e9f?w=500',
      cuisine: 'Fast Food',
      rating: 4.5,
      reviewCount: 150,
      deliveryTime: '20-40 min',
      deliveryFee: 2.99,
      minimumOrder: 10.0,
      distance: 2.5,
      featured: true,
      isOpen: true,
    ),
    Restaurant(
      id: 'r14',
      name: 'Lahore Tikka',
      image: 'https://images.unsplash.com/photo-1599487405270-864f134591a2?w=500',
      cuisine: 'BBQ',
      rating: 4.5,
      reviewCount: 150,
      deliveryTime: '20-40 min',
      deliveryFee: 2.99,
      minimumOrder: 10.0,
      distance: 2.5,
      featured: true,
      isOpen: true,
    ),
    Restaurant(
      id: 'r15',
      name: 'Daily Dine',
      image: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=500',
      cuisine: 'Breakfast',
      rating: 4.5,
      reviewCount: 150,
      deliveryTime: '20-40 min',
      deliveryFee: 2.99,
      minimumOrder: 10.0,
      distance: 2.5,
      featured: true,
      isOpen: true,
    ),
  ];

  static final List<FoodItem> foods = [
    FoodItem(
      id: 'f1',
      restaurantId: 'r1',
      name: 'Chicken Biryani',
      description: 'Delicious Chicken Biryani',
      image: 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?w=500',
      price: 5.99,
      category: 'Pakistani',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f2',
      restaurantId: 'r1',
      name: 'Beef Biryani',
      description: 'Delicious Beef Biryani',
      image: 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?w=500',
      price: 6.99,
      category: 'Pakistani',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f3',
      restaurantId: 'r1',
      name: 'Chicken Karahi',
      description: 'Delicious Chicken Karahi',
      image: 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?w=500',
      price: 7.99,
      category: 'Pakistani',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f4',
      restaurantId: 'r1',
      name: 'Mutton Nihari',
      description: 'Delicious Mutton Nihari',
      image: 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?w=500',
      price: 8.99,
      category: 'Pakistani',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f5',
      restaurantId: 'r1',
      name: 'Haleem',
      description: 'Delicious Haleem',
      image: 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?w=500',
      price: 9.99,
      category: 'Pakistani',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f6',
      restaurantId: 'r1',
      name: 'Chapli Kabab',
      description: 'Delicious Chapli Kabab',
      image: 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?w=500',
      price: 10.99,
      category: 'Pakistani',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f7',
      restaurantId: 'r1',
      name: 'Seekh Kabab',
      description: 'Delicious Seekh Kabab',
      image: 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?w=500',
      price: 11.99,
      category: 'Pakistani',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f8',
      restaurantId: 'r1',
      name: 'Naan',
      description: 'Delicious Naan',
      image: 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?w=500',
      price: 12.99,
      category: 'Pakistani',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f9',
      restaurantId: 'r2',
      name: 'Zinger Burger',
      description: 'Delicious Zinger Burger',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500',
      price: 5.99,
      category: 'Fast Food',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f10',
      restaurantId: 'r2',
      name: 'Beef Burger',
      description: 'Delicious Beef Burger',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500',
      price: 6.99,
      category: 'Fast Food',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f11',
      restaurantId: 'r2',
      name: 'Loaded Fries',
      description: 'Delicious Loaded Fries',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500',
      price: 7.99,
      category: 'Fast Food',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f12',
      restaurantId: 'r2',
      name: 'Chicken Wrap',
      description: 'Delicious Chicken Wrap',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500',
      price: 8.99,
      category: 'Fast Food',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f13',
      restaurantId: 'r2',
      name: 'Club Sandwich',
      description: 'Delicious Club Sandwich',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500',
      price: 9.99,
      category: 'Fast Food',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f14',
      restaurantId: 'r2',
      name: 'Fried Chicken',
      description: 'Delicious Fried Chicken',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500',
      price: 10.99,
      category: 'Fast Food',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f15',
      restaurantId: 'r2',
      name: 'Chicken Nuggets',
      description: 'Delicious Chicken Nuggets',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500',
      price: 11.99,
      category: 'Fast Food',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f16',
      restaurantId: 'r2',
      name: 'Onion Rings',
      description: 'Delicious Onion Rings',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500',
      price: 12.99,
      category: 'Fast Food',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f17',
      restaurantId: 'r3',
      name: 'Chicken Tikka',
      description: 'Delicious Chicken Tikka',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?w=500',
      price: 5.99,
      category: 'BBQ',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f18',
      restaurantId: 'r3',
      name: 'Beef Boti',
      description: 'Delicious Beef Boti',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?w=500',
      price: 6.99,
      category: 'BBQ',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f19',
      restaurantId: 'r3',
      name: 'Malai Boti',
      description: 'Delicious Malai Boti',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?w=500',
      price: 7.99,
      category: 'BBQ',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f20',
      restaurantId: 'r3',
      name: 'Seekh Kabab',
      description: 'Delicious Seekh Kabab',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?w=500',
      price: 8.99,
      category: 'BBQ',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f21',
      restaurantId: 'r3',
      name: 'Mutton Ribs',
      description: 'Delicious Mutton Ribs',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?w=500',
      price: 9.99,
      category: 'BBQ',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f22',
      restaurantId: 'r3',
      name: 'Bihari Kabab',
      description: 'Delicious Bihari Kabab',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?w=500',
      price: 10.99,
      category: 'BBQ',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f23',
      restaurantId: 'r3',
      name: 'Reshmi Kabab',
      description: 'Delicious Reshmi Kabab',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?w=500',
      price: 11.99,
      category: 'BBQ',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f24',
      restaurantId: 'r3',
      name: 'Fish Tikka',
      description: 'Delicious Fish Tikka',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?w=500',
      price: 12.99,
      category: 'BBQ',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f25',
      restaurantId: 'r4',
      name: 'Cheese Pizza',
      description: 'Delicious Cheese Pizza',
      image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500',
      price: 5.99,
      category: 'Pizza',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f26',
      restaurantId: 'r4',
      name: 'Pepperoni Pizza',
      description: 'Delicious Pepperoni Pizza',
      image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500',
      price: 6.99,
      category: 'Pizza',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f27',
      restaurantId: 'r4',
      name: 'Chicken Fajita Pizza',
      description: 'Delicious Chicken Fajita Pizza',
      image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500',
      price: 7.99,
      category: 'Pizza',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f28',
      restaurantId: 'r4',
      name: 'BBQ Chicken Pizza',
      description: 'Delicious BBQ Chicken Pizza',
      image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500',
      price: 8.99,
      category: 'Pizza',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f29',
      restaurantId: 'r4',
      name: 'Veggie Supreme Pizza',
      description: 'Delicious Veggie Supreme Pizza',
      image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500',
      price: 9.99,
      category: 'Pizza',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f30',
      restaurantId: 'r4',
      name: 'Margherita Pizza',
      description: 'Delicious Margherita Pizza',
      image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500',
      price: 10.99,
      category: 'Pizza',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f31',
      restaurantId: 'r4',
      name: 'Meat Lovers Pizza',
      description: 'Delicious Meat Lovers Pizza',
      image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500',
      price: 11.99,
      category: 'Pizza',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f32',
      restaurantId: 'r4',
      name: 'Hawaiian Pizza',
      description: 'Delicious Hawaiian Pizza',
      image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500',
      price: 12.99,
      category: 'Pizza',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f33',
      restaurantId: 'r5',
      name: 'Classic Beef Burger',
      description: 'Delicious Classic Beef Burger',
      image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=500',
      price: 5.99,
      category: 'Burgers',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f34',
      restaurantId: 'r5',
      name: 'Cheeseburger',
      description: 'Delicious Cheeseburger',
      image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=500',
      price: 6.99,
      category: 'Burgers',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f35',
      restaurantId: 'r5',
      name: 'Double Decker',
      description: 'Delicious Double Decker',
      image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=500',
      price: 7.99,
      category: 'Burgers',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f36',
      restaurantId: 'r5',
      name: 'Chicken Fillet Burger',
      description: 'Delicious Chicken Fillet Burger',
      image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=500',
      price: 8.99,
      category: 'Burgers',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f37',
      restaurantId: 'r5',
      name: 'Mushroom Swiss Burger',
      description: 'Delicious Mushroom Swiss Burger',
      image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=500',
      price: 9.99,
      category: 'Burgers',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f38',
      restaurantId: 'r5',
      name: 'Spicy Jalapeno Burger',
      description: 'Delicious Spicy Jalapeno Burger',
      image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=500',
      price: 10.99,
      category: 'Burgers',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f39',
      restaurantId: 'r5',
      name: 'Veggie Burger',
      description: 'Delicious Veggie Burger',
      image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=500',
      price: 11.99,
      category: 'Burgers',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f40',
      restaurantId: 'r5',
      name: 'BBQ Bacon Burger',
      description: 'Delicious BBQ Bacon Burger',
      image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=500',
      price: 12.99,
      category: 'Burgers',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f41',
      restaurantId: 'r6',
      name: 'Chicken Tikka',
      description: 'Delicious Chicken Tikka',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?w=500',
      price: 5.99,
      category: 'BBQ',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f42',
      restaurantId: 'r6',
      name: 'Beef Boti',
      description: 'Delicious Beef Boti',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?w=500',
      price: 6.99,
      category: 'BBQ',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f43',
      restaurantId: 'r6',
      name: 'Malai Boti',
      description: 'Delicious Malai Boti',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?w=500',
      price: 7.99,
      category: 'BBQ',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f44',
      restaurantId: 'r6',
      name: 'Seekh Kabab',
      description: 'Delicious Seekh Kabab',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?w=500',
      price: 8.99,
      category: 'BBQ',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f45',
      restaurantId: 'r6',
      name: 'Mutton Ribs',
      description: 'Delicious Mutton Ribs',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?w=500',
      price: 9.99,
      category: 'BBQ',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f46',
      restaurantId: 'r6',
      name: 'Bihari Kabab',
      description: 'Delicious Bihari Kabab',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?w=500',
      price: 10.99,
      category: 'BBQ',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f47',
      restaurantId: 'r6',
      name: 'Reshmi Kabab',
      description: 'Delicious Reshmi Kabab',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?w=500',
      price: 11.99,
      category: 'BBQ',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f48',
      restaurantId: 'r6',
      name: 'Fish Tikka',
      description: 'Delicious Fish Tikka',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?w=500',
      price: 12.99,
      category: 'BBQ',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f49',
      restaurantId: 'r7',
      name: 'Chicken Biryani',
      description: 'Delicious Chicken Biryani',
      image: 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?w=500',
      price: 5.99,
      category: 'Pakistani',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f50',
      restaurantId: 'r7',
      name: 'Beef Biryani',
      description: 'Delicious Beef Biryani',
      image: 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?w=500',
      price: 6.99,
      category: 'Pakistani',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f51',
      restaurantId: 'r7',
      name: 'Chicken Karahi',
      description: 'Delicious Chicken Karahi',
      image: 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?w=500',
      price: 7.99,
      category: 'Pakistani',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f52',
      restaurantId: 'r7',
      name: 'Mutton Nihari',
      description: 'Delicious Mutton Nihari',
      image: 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?w=500',
      price: 8.99,
      category: 'Pakistani',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f53',
      restaurantId: 'r7',
      name: 'Haleem',
      description: 'Delicious Haleem',
      image: 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?w=500',
      price: 9.99,
      category: 'Pakistani',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f54',
      restaurantId: 'r7',
      name: 'Chapli Kabab',
      description: 'Delicious Chapli Kabab',
      image: 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?w=500',
      price: 10.99,
      category: 'Pakistani',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f55',
      restaurantId: 'r7',
      name: 'Seekh Kabab',
      description: 'Delicious Seekh Kabab',
      image: 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?w=500',
      price: 11.99,
      category: 'Pakistani',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f56',
      restaurantId: 'r7',
      name: 'Naan',
      description: 'Delicious Naan',
      image: 'https://images.unsplash.com/photo-1589302168068-964664d93cb0?w=500',
      price: 12.99,
      category: 'Pakistani',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f57',
      restaurantId: 'r8',
      name: 'Chow Mein',
      description: 'Delicious Chow Mein',
      image: 'https://images.unsplash.com/photo-1552611052-33e04de081de?w=500',
      price: 5.99,
      category: 'Chinese',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f58',
      restaurantId: 'r8',
      name: 'Chicken Fried Rice',
      description: 'Delicious Chicken Fried Rice',
      image: 'https://images.unsplash.com/photo-1552611052-33e04de081de?w=500',
      price: 6.99,
      category: 'Chinese',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f59',
      restaurantId: 'r8',
      name: 'Spring Rolls',
      description: 'Delicious Spring Rolls',
      image: 'https://images.unsplash.com/photo-1552611052-33e04de081de?w=500',
      price: 7.99,
      category: 'Chinese',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f60',
      restaurantId: 'r8',
      name: 'Sweet and Sour Chicken',
      description: 'Delicious Sweet and Sour Chicken',
      image: 'https://images.unsplash.com/photo-1552611052-33e04de081de?w=500',
      price: 8.99,
      category: 'Chinese',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f61',
      restaurantId: 'r8',
      name: 'Kung Pao Chicken',
      description: 'Delicious Kung Pao Chicken',
      image: 'https://images.unsplash.com/photo-1552611052-33e04de081de?w=500',
      price: 9.99,
      category: 'Chinese',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f62',
      restaurantId: 'r8',
      name: 'Manchurian',
      description: 'Delicious Manchurian',
      image: 'https://images.unsplash.com/photo-1552611052-33e04de081de?w=500',
      price: 10.99,
      category: 'Chinese',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f63',
      restaurantId: 'r8',
      name: 'Egg Drop Soup',
      description: 'Delicious Egg Drop Soup',
      image: 'https://images.unsplash.com/photo-1552611052-33e04de081de?w=500',
      price: 11.99,
      category: 'Chinese',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f64',
      restaurantId: 'r8',
      name: 'Dumplings',
      description: 'Delicious Dumplings',
      image: 'https://images.unsplash.com/photo-1552611052-33e04de081de?w=500',
      price: 12.99,
      category: 'Chinese',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f65',
      restaurantId: 'r9',
      name: 'Chocolate Cake',
      description: 'Delicious Chocolate Cake',
      image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=500',
      price: 5.99,
      category: 'Desserts',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f66',
      restaurantId: 'r9',
      name: 'Brownie',
      description: 'Delicious Brownie',
      image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=500',
      price: 6.99,
      category: 'Desserts',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f67',
      restaurantId: 'r9',
      name: 'Ice Cream Sundae',
      description: 'Delicious Ice Cream Sundae',
      image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=500',
      price: 7.99,
      category: 'Desserts',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f68',
      restaurantId: 'r9',
      name: 'Cheesecake',
      description: 'Delicious Cheesecake',
      image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=500',
      price: 8.99,
      category: 'Desserts',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f69',
      restaurantId: 'r9',
      name: 'Gulab Jamun',
      description: 'Delicious Gulab Jamun',
      image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=500',
      price: 9.99,
      category: 'Desserts',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f70',
      restaurantId: 'r9',
      name: 'Rasmalai',
      description: 'Delicious Rasmalai',
      image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=500',
      price: 10.99,
      category: 'Desserts',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f71',
      restaurantId: 'r9',
      name: 'Fruit Trifle',
      description: 'Delicious Fruit Trifle',
      image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=500',
      price: 11.99,
      category: 'Desserts',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f72',
      restaurantId: 'r9',
      name: 'Lava Cake',
      description: 'Delicious Lava Cake',
      image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=500',
      price: 12.99,
      category: 'Desserts',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f73',
      restaurantId: 'r10',
      name: 'Samosa',
      description: 'Delicious Samosa',
      image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=500',
      price: 5.99,
      category: 'Snacks',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f74',
      restaurantId: 'r10',
      name: 'Pakora',
      description: 'Delicious Pakora',
      image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=500',
      price: 6.99,
      category: 'Snacks',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f75',
      restaurantId: 'r10',
      name: 'Fries',
      description: 'Delicious Fries',
      image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=500',
      price: 7.99,
      category: 'Snacks',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f76',
      restaurantId: 'r10',
      name: 'Nachos',
      description: 'Delicious Nachos',
      image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=500',
      price: 8.99,
      category: 'Snacks',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f77',
      restaurantId: 'r10',
      name: 'Chicken Wings',
      description: 'Delicious Chicken Wings',
      image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=500',
      price: 9.99,
      category: 'Snacks',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f78',
      restaurantId: 'r10',
      name: 'Garlic Bread',
      description: 'Delicious Garlic Bread',
      image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=500',
      price: 10.99,
      category: 'Snacks',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f79',
      restaurantId: 'r10',
      name: 'Mozzarella Sticks',
      description: 'Delicious Mozzarella Sticks',
      image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=500',
      price: 11.99,
      category: 'Snacks',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f80',
      restaurantId: 'r10',
      name: 'Chaat',
      description: 'Delicious Chaat',
      image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=500',
      price: 12.99,
      category: 'Snacks',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f81',
      restaurantId: 'r11',
      name: 'Grilled Chicken Salad',
      description: 'Delicious Grilled Chicken Salad',
      image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500',
      price: 5.99,
      category: 'Healthy',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f82',
      restaurantId: 'r11',
      name: 'Quinoa Bowl',
      description: 'Delicious Quinoa Bowl',
      image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500',
      price: 6.99,
      category: 'Healthy',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f83',
      restaurantId: 'r11',
      name: 'Fruit Salad',
      description: 'Delicious Fruit Salad',
      image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500',
      price: 7.99,
      category: 'Healthy',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f84',
      restaurantId: 'r11',
      name: 'Avocado Toast',
      description: 'Delicious Avocado Toast',
      image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500',
      price: 8.99,
      category: 'Healthy',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f85',
      restaurantId: 'r11',
      name: 'Green Smoothie',
      description: 'Delicious Green Smoothie',
      image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500',
      price: 9.99,
      category: 'Healthy',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f86',
      restaurantId: 'r11',
      name: 'Oatmeal',
      description: 'Delicious Oatmeal',
      image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500',
      price: 10.99,
      category: 'Healthy',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f87',
      restaurantId: 'r11',
      name: 'Vegetable Stir Fry',
      description: 'Delicious Vegetable Stir Fry',
      image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500',
      price: 11.99,
      category: 'Healthy',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f88',
      restaurantId: 'r11',
      name: 'Baked Salmon',
      description: 'Delicious Baked Salmon',
      image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500',
      price: 12.99,
      category: 'Healthy',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f89',
      restaurantId: 'r12',
      name: 'Milkshake',
      description: 'Delicious Milkshake',
      image: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=500',
      price: 5.99,
      category: 'Drinks',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f90',
      restaurantId: 'r12',
      name: 'Cold Coffee',
      description: 'Delicious Cold Coffee',
      image: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=500',
      price: 6.99,
      category: 'Drinks',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f91',
      restaurantId: 'r12',
      name: 'Fresh Juice',
      description: 'Delicious Fresh Juice',
      image: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=500',
      price: 7.99,
      category: 'Drinks',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f92',
      restaurantId: 'r12',
      name: 'Lemonade',
      description: 'Delicious Lemonade',
      image: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=500',
      price: 8.99,
      category: 'Drinks',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f93',
      restaurantId: 'r12',
      name: 'Iced Tea',
      description: 'Delicious Iced Tea',
      image: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=500',
      price: 9.99,
      category: 'Drinks',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f94',
      restaurantId: 'r12',
      name: 'Cappuccino',
      description: 'Delicious Cappuccino',
      image: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=500',
      price: 10.99,
      category: 'Drinks',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f95',
      restaurantId: 'r12',
      name: 'Lassi',
      description: 'Delicious Lassi',
      image: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=500',
      price: 11.99,
      category: 'Drinks',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f96',
      restaurantId: 'r12',
      name: 'Mint Margarita',
      description: 'Delicious Mint Margarita',
      image: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=500',
      price: 12.99,
      category: 'Drinks',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f97',
      restaurantId: 'r13',
      name: 'Zinger Burger',
      description: 'Delicious Zinger Burger',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500',
      price: 5.99,
      category: 'Fast Food',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f98',
      restaurantId: 'r13',
      name: 'Beef Burger',
      description: 'Delicious Beef Burger',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500',
      price: 6.99,
      category: 'Fast Food',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f99',
      restaurantId: 'r13',
      name: 'Loaded Fries',
      description: 'Delicious Loaded Fries',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500',
      price: 7.99,
      category: 'Fast Food',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f100',
      restaurantId: 'r13',
      name: 'Chicken Wrap',
      description: 'Delicious Chicken Wrap',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500',
      price: 8.99,
      category: 'Fast Food',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f101',
      restaurantId: 'r13',
      name: 'Club Sandwich',
      description: 'Delicious Club Sandwich',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500',
      price: 9.99,
      category: 'Fast Food',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f102',
      restaurantId: 'r13',
      name: 'Fried Chicken',
      description: 'Delicious Fried Chicken',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500',
      price: 10.99,
      category: 'Fast Food',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f103',
      restaurantId: 'r13',
      name: 'Chicken Nuggets',
      description: 'Delicious Chicken Nuggets',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500',
      price: 11.99,
      category: 'Fast Food',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f104',
      restaurantId: 'r13',
      name: 'Onion Rings',
      description: 'Delicious Onion Rings',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500',
      price: 12.99,
      category: 'Fast Food',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f105',
      restaurantId: 'r14',
      name: 'Chicken Tikka',
      description: 'Delicious Chicken Tikka',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?w=500',
      price: 5.99,
      category: 'BBQ',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f106',
      restaurantId: 'r14',
      name: 'Beef Boti',
      description: 'Delicious Beef Boti',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?w=500',
      price: 6.99,
      category: 'BBQ',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f107',
      restaurantId: 'r14',
      name: 'Malai Boti',
      description: 'Delicious Malai Boti',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?w=500',
      price: 7.99,
      category: 'BBQ',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f108',
      restaurantId: 'r14',
      name: 'Seekh Kabab',
      description: 'Delicious Seekh Kabab',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?w=500',
      price: 8.99,
      category: 'BBQ',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f109',
      restaurantId: 'r14',
      name: 'Mutton Ribs',
      description: 'Delicious Mutton Ribs',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?w=500',
      price: 9.99,
      category: 'BBQ',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f110',
      restaurantId: 'r14',
      name: 'Bihari Kabab',
      description: 'Delicious Bihari Kabab',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?w=500',
      price: 10.99,
      category: 'BBQ',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f111',
      restaurantId: 'r14',
      name: 'Reshmi Kabab',
      description: 'Delicious Reshmi Kabab',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?w=500',
      price: 11.99,
      category: 'BBQ',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f112',
      restaurantId: 'r14',
      name: 'Fish Tikka',
      description: 'Delicious Fish Tikka',
      image: 'https://images.unsplash.com/photo-1544025162-8111149c4398?w=500',
      price: 12.99,
      category: 'BBQ',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f113',
      restaurantId: 'r15',
      name: 'Pancakes',
      description: 'Delicious Pancakes',
      image: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=500',
      price: 5.99,
      category: 'Breakfast',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f114',
      restaurantId: 'r15',
      name: 'Omelette',
      description: 'Delicious Omelette',
      image: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=500',
      price: 6.99,
      category: 'Breakfast',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f115',
      restaurantId: 'r15',
      name: 'Waffles',
      description: 'Delicious Waffles',
      image: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=500',
      price: 7.99,
      category: 'Breakfast',
      rating: 4.6,
      popular: true,
      available: true,
    ),
    FoodItem(
      id: 'f116',
      restaurantId: 'r15',
      name: 'French Toast',
      description: 'Delicious French Toast',
      image: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=500',
      price: 8.99,
      category: 'Breakfast',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f117',
      restaurantId: 'r15',
      name: 'Halwa Puri',
      description: 'Delicious Halwa Puri',
      image: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=500',
      price: 9.99,
      category: 'Breakfast',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f118',
      restaurantId: 'r15',
      name: 'Aloo Paratha',
      description: 'Delicious Aloo Paratha',
      image: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=500',
      price: 10.99,
      category: 'Breakfast',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f119',
      restaurantId: 'r15',
      name: 'Scrambled Eggs',
      description: 'Delicious Scrambled Eggs',
      image: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=500',
      price: 11.99,
      category: 'Breakfast',
      rating: 4.6,
      popular: false,
      available: true,
    ),
    FoodItem(
      id: 'f120',
      restaurantId: 'r15',
      name: 'Hash Browns',
      description: 'Delicious Hash Browns',
      image: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=500',
      price: 12.99,
      category: 'Breakfast',
      rating: 4.6,
      popular: false,
      available: true,
    ),
  ];

  static final List<Coupon> coupons = [
    Coupon(code: 'WELCOME10', discountValue: 10, isPercentage: true, minOrderAmount: 20),
    Coupon(code: 'FLAT5', discountValue: 5, isPercentage: false, minOrderAmount: 15),
  ];
}
